#include <stdio.h>
#include "UIFlow.h"

// --------------------------------------------------------------------------
// OPTIONS
// --------------------------------------------------------------------------
// MOVIE_SIZE_TAG
// Movie Size Options
TMDEF_BEGIN_OPTIONS(MOVIE_SIZE)
#if (WIFI_FINALCAM_APP_STYLE == DISABLE)
//#NT#2016/08/12#Hideo Lin -begin
//#NT#For small size clone movie
#if (SMALL_CLONE_MOVIE == DISABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)	/// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_ENABLE)		/// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)	/// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)	/// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)	/// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_ENABLE)		/// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)	/// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)	/// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_ENABLE)		/// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)	/// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_ENABLE)		/// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_ENABLE)		/// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_ENABLE)		/// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_NOT_SUPPORT)	/// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_ENABLE)		/// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_ENABLE)		/// HD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_NOT_SUPPORT)	/// WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)	/// VGA P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_NOT_SUPPORT)	/// VGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)	/// QVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_ENABLE)		/// FHD FHD
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_TRI_1920x1080P30,				TM_OPTION_ENABLE)		/// FHD x 3
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_QUAD_1920x1080P30,				TM_OPTION_ENABLE)		/// FHD x 4
#else
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)  /// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_NOT_SUPPORT)  /// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)  /// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)  /// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)  /// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_NOT_SUPPORT)  /// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)  /// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)  /// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_NOT_SUPPORT)  /// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)  /// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_NOT_SUPPORT)  /// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_NOT_SUPPORT)  /// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_NOT_SUPPORT)  /// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_NOT_SUPPORT)  /// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_NOT_SUPPORT)  /// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_NOT_SUPPORT)  /// HD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_NOT_SUPPORT)  /// WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)  /// VGA P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_NOT_SUPPORT)  /// VGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)  /// QVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_NOT_SUPPORT)  /// FHD FHD
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_TRI_1920x1080P30,				TM_OPTION_NOT_SUPPORT)	/// FHD x 3
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_QUAD_1920x1080P30,				TM_OPTION_NOT_SUPPORT)	/// FHD x 4
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_1920x1080P30, TM_OPTION_NOT_SUPPORT)  /// FHD P30 + FHD  P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_1280x720P30,  TM_OPTION_NOT_SUPPORT)  /// FHD P30 + HD   P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_2560x1440P30_848x480P30,   TM_OPTION_ENABLE)       /// QHD P30 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_2304x1296P30_848x480P30,   TM_OPTION_ENABLE)       /// 3M  P30 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P60_848x480P30,   TM_OPTION_ENABLE)       /// FHD P60 + WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P60_640x360P30,   TM_OPTION_NOT_SUPPORT)  /// FHD P60 + VGA  P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_CLONE_1920x1080P30_848x480P30,   TM_OPTION_ENABLE)       /// FHD P30 + WVGA P30
#endif
//#NT#2016/08/12#Hideo Lin -end
#else
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P50,              TM_OPTION_NOT_SUPPORT)  /// UHD P50 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_3840x2160P30,              TM_OPTION_NOT_SUPPORT)  /// UHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2880x2160P24,              TM_OPTION_NOT_SUPPORT)  /// UHD P24 (DAR)
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2704x2032P60,              TM_OPTION_NOT_SUPPORT)  /// 2.7K P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P80,              TM_OPTION_NOT_SUPPORT)  /// QHD P80
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P60,              TM_OPTION_NOT_SUPPORT)  /// QHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2560x1440P30,              TM_OPTION_NOT_SUPPORT)  /// QHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_2304x1296P30,              TM_OPTION_NOT_SUPPORT)  /// 3MHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P120,             TM_OPTION_NOT_SUPPORT)  /// FHD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P96,              TM_OPTION_NOT_SUPPORT)  /// FHD P96
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P60,              TM_OPTION_NOT_SUPPORT)  /// FHD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1920x1080P30,              TM_OPTION_ENABLE)       /// FHD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P240,              TM_OPTION_NOT_SUPPORT)  /// HD P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P120,              TM_OPTION_NOT_SUPPORT)  /// HD P120
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P60,               TM_OPTION_NOT_SUPPORT)  /// HD P60
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_1280x720P30,               TM_OPTION_ENABLE)       /// HD P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_848x480P30,                TM_OPTION_ENABLE)       /// WVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P240,               TM_OPTION_NOT_SUPPORT)  /// VGA P240
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_640x480P30,                TM_OPTION_ENABLE)       /// VGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_FRONT_320x240P30,                TM_OPTION_NOT_SUPPORT)  /// QVGA P30
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30,  TM_OPTION_NOT_SUPPORT)  /// FHD FHD
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_TRI_1920x1080P30,				TM_OPTION_NOT_SUPPORT)	/// FHD x 3
TMDEF_OPTION_TEXT_S(MOVIE_SIZE_QUAD_1920x1080P30,				TM_OPTION_NOT_SUPPORT)	/// FHD x 4
#endif
TMDEF_END_OPTIONS()

// Cyclic recroding Options
TMDEF_BEGIN_OPTIONS(MOVIE_CYCLIC_REC)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_1MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_3MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_5MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_CYCLIC_REC_10MIN, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_HDR)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_HDR_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_WDR)
TMDEF_OPTION_TEXT_S(MOVIE_WDR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_WDR_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_MOTION_DET)
TMDEF_OPTION_TEXT_S(MOVIE_MOTION_DET_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_MOTION_DET_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_AUDIO)
TMDEF_OPTION_TEXT_S(MOVIE_AUDIO_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_AUDIO_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DATEIMPRINT)
TMDEF_OPTION_TEXT_S(MOVIE_DATEIMPRINT_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DATEIMPRINT_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_RSC)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_RSC_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_GSENSOR)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_LOW, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_MED, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_GSENSOR_HIGH, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_TIMELAPSE_REC)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_5SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_10SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_30SEC, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_5MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_10MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_30MIN, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1HOUR, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_2HOUR, TM_OPTION_NOT_SUPPORT)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_3HOUR, TM_OPTION_NOT_SUPPORT)
TMDEF_OPTION_TEXT_S(MOVIE_TIMELAPSE_REC_1DAY, TM_OPTION_NOT_SUPPORT)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_IR_CUT)
TMDEF_OPTION_TEXT_S(MOVIE_IR_CUT_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_IR_CUT_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_SENSOR_ROTATE)
TMDEF_OPTION_TEXT_S(MOVIE_SENSOR_ROTATE_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_SENSOR_ROTATE_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_PTZ)
TMDEF_OPTION_TEXT_S(MOVIE_PTZ_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_PTZ_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_URGENT_PROTECT_AUTO)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_AUTO_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_AUTO_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_URGENT_PROTECT_MANUAL)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_MANUAL_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_URGENT_PROTECT_MANUAL_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_PIM)
TMDEF_OPTION_TEXT_S(MOVIE_PIM_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_PIM_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_LDWS)
TMDEF_OPTION_TEXT_S(MOVIE_LDWS_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_LDWS_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_FCW)
TMDEF_OPTION_TEXT_S(MOVIE_FCW_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_FCW_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DDD)
TMDEF_OPTION_TEXT_S(MOVIE_DDD_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DDD_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_ADAS_CAL)
TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_OFF, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_ADAS_CAL_ON, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_DUAL_CAM)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_FRONT, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BEHIND, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BOTH, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_DUAL_CAM_BOTH2, TM_OPTION_ENABLE)
TMDEF_END_OPTIONS()

TMDEF_BEGIN_OPTIONS(MOVIE_CODEC)
TMDEF_OPTION_TEXT_S(MOVIE_H264, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_H265, TM_OPTION_ENABLE)
TMDEF_OPTION_TEXT_S(MOVIE_MJPG, TM_OPTION_DISABLE)
TMDEF_END_OPTIONS()

// --------------------------------------------------------------------------
// ITEMS
// --------------------------------------------------------------------------
// Movie Menu Items
TMDEF_BEGIN_ITEMS(MOVIE)
TMDEF_ITEM_TEXTID(MOVIE_SIZE)
TMDEF_ITEM_TEXTID(MOVIE_CYCLIC_REC)
#if (SHDR_FUNC == ENABLE)
TMDEF_ITEM_TEXTID(MOVIE_HDR)
#endif
TMDEF_ITEM_TEXTID(MOVIE_WDR)
TMDEF_ITEM_TEXTID(EV)
TMDEF_ITEM_TEXTID(MOVIE_MOTION_DET)
TMDEF_ITEM_TEXTID(MOVIE_AUDIO)
TMDEF_ITEM_TEXTID(MOVIE_DATEIMPRINT)
#if (MOVIE_RSC == ENABLE)
TMDEF_ITEM_TEXTID(MOVIE_RSC)
#endif
TMDEF_ITEM_TEXTID(MOVIE_GSENSOR)
TMDEF_ITEM_TEXTID(MOVIE_TIMELAPSE_REC)
TMDEF_ITEM_TEXTID(MOVIE_IR_CUT)
TMDEF_ITEM_TEXTID(MOVIE_SENSOR_ROTATE)
TMDEF_ITEM_TEXTID(MOVIE_PTZ)
TMDEF_ITEM_TEXTID(MOVIE_URGENT_PROTECT_AUTO)
TMDEF_ITEM_TEXTID(MOVIE_URGENT_PROTECT_MANUAL)
TMDEF_ITEM_TEXTID(MOVIE_PIM)
TMDEF_ITEM_TEXTID(MOVIE_LDWS)
TMDEF_ITEM_TEXTID(MOVIE_FCW)
TMDEF_ITEM_TEXTID(MOVIE_DDD)
TMDEF_ITEM_TEXTID(MOVIE_ADAS_CAL)
#if (SENSOR_CAPS_COUNT > 1)
TMDEF_ITEM_TEXTID(MOVIE_DUAL_CAM)
#endif
TMDEF_ITEM_TEXTID(MOVIE_CODEC)
TMDEF_END_ITEMS()

// --------------------------------------------------------------------------
// PAGES
// --------------------------------------------------------------------------
// Movie Menu Pages
TMDEF_BEGIN_PAGES(MOVIE)
TMDEF_PAGE_TEXT_ICON(MOVIE)
TMDEF_END_PAGES()

TMDEF_EMNU(gMovieMenu, MOVIE, Movie_MenuCallback)

// --------------------------------------------------------------------------
// Menu Callback
// --------------------------------------------------------------------------
int Movie_MenuCallback(UINT32 uiMessage, UINT32 uiParam)
{
	UINT16  uwItemId;
	UINT16  uwOption;

	if (uiMessage == TMM_CONFIRM_OPTION) {
		uwItemId = LO_WORD(uiParam);
		uwOption = HI_WORD(uiParam);

		switch (uwItemId) {
		case IDM_MOVIE_SIZE:
			//Set Movie size event until menu is closed.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, uwOption);
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_IMAGE_RATIO, 1, GetMovieSizeRatio(UI_GetData(FL_MOVIE_SIZE)));
			break;

		case IDM_MOVIE_CYCLIC_REC:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_CYCLIC_REC, 1, uwOption);
			break;

		case IDM_MOVIE_WDR:
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_WDR, 1, uwOption);
			break;

		case IDM_MOVIE_HDR:
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_SHDR, 1, uwOption);
			break;

		case IDM_EV:
			Ux_SendEvent(&CustomPhotoObjCtrl, NVTEVT_EXE_EV, 1, uwOption);
			break;

		case IDM_MOVIE_MOTION_DET:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOTION_DET, 1, uwOption);
			break;

		case IDM_MOVIE_AUDIO:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_AUDIO, 1, uwOption);
			break;

		case IDM_MOVIE_DATEIMPRINT:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_DATE_IMPRINT, 1, uwOption);
			break;

		case IDM_MOVIE_RSC:
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_RSC, 1, uwOption);
			break;
		case IDM_MOVIE_GSENSOR:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_GSENSOR, 1, uwOption);
			break;
		case IDM_MOVIE_TIMELAPSE_REC:
			//#NT#2016/09/20#KCHong -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//SysSetFlag(FL_MOVIE_TIMELAPSE_REC,uwOption);
			//#NT#2016/09/20#KCHong -end
			break;

		case IDM_MOVIE_IR_CUT:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_IR_CUT, 1, uwOption);
			break;

		case IDM_MOVIE_SENSOR_ROTATE:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_SENSOR_ROTATE, 1, uwOption);
			break;

		case IDM_MOVIE_PTZ:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PTZ, 1, uwOption);
			break;

		case IDM_MOVIE_URGENT_PROTECT_AUTO:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PROTECT_AUTO, 1, uwOption);
			break;

		case IDM_MOVIE_URGENT_PROTECT_MANUAL:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_PROTECT_MANUAL, 1, uwOption);
			break;

		case IDM_MOVIE_PIM:
			SysSetFlag(FL_MOVIE_PIM, uwOption);
			break;

		case IDM_MOVIE_LDWS:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_LDWS, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
			break;

		case IDM_MOVIE_FCW:
			//#NT#2016/10/12#KCHong#[0111054] -begin
			//#NT#Don't set flag here if use both FL_XXX_MENU and FL_XXX to store status.
			//Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_FCW, 1, uwOption);
			//#NT#2016/10/12#KCHong#[0111054] -end
			break;

		case IDM_MOVIE_DDD:
			break;

		case IDM_MOVIE_DUAL_CAM:
			break;
		case IDM_MOVIE_ADAS_CAL:

			break;
		case IDM_MOVIE_CODEC:
			Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_CODEC, 1, uwOption);
			break;

		default:
			//Setup_MenuCallback(uiMessage, uiParam);
			break;
		}
	}

	return TMF_PROCESSED;
}
