#
# Include uitron related setting
#

include $(NVT_PRJCFG_MODEL_CFG)
include $(NVT_PRJCFG_MODEL_MK)

PLATFORM_CPPFLAGS += $(C_DEFINE_EXT)
PLATFORM_CPPFLAGS += -I$(INCLUDE_DIR) -DCONFIG_SYS_TEXT_BASE=$(BOARD_UBOOT_ADDR)
