//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOEXPOSURE_H
#define UIMENUWNDPHOTOEXPOSURE_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoExposureCtrl;//Panel type

extern VControl UIMenuWndPhotoExposure_PanelCtrl;//Panel type

extern VControl UIMenuWndPhotoExposure_MenuCtrl;//Menu type

typedef enum {
	UIMenuWndPhotoExposure_Menu_STRID_EV_P2P0,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P1P6,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P1P3,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P1P0,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P0P6,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P0P3,
	UIMenuWndPhotoExposure_Menu_STRID_EV_P0P0,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M0P3,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M0P6,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M1P0,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M1P3,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M1P6,
	UIMenuWndPhotoExposure_Menu_STRID_EV_M2P0,
	UIMenuWndPhotoExposure_Menu_MAX
} UIMenuWndPhotoExposure_Menu_Setting;

#endif
