//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOWB_H
#define UIMENUWNDPHOTOWB_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoWBCtrl;//Panel type

extern VControl UIMenuWndPhotoWB_PanelCtrl;//Panel type

extern VControl UIMenuWndPhotoWB_MenuCtrl;//Menu type

typedef enum {
	UIMenuWndPhotoWB_Menu_STRID_AUTO,
	UIMenuWndPhotoWB_Menu_STRID_WB_DAY,
	UIMenuWndPhotoWB_Menu_STRID_WB_CLOUDY,
	UIMenuWndPhotoWB_Menu_STRID_WB_TUNGSTEN,
	UIMenuWndPhotoWB_Menu_STRID_WB_FLUORESCENT,
	UIMenuWndPhotoWB_Menu_MAX
} UIMenuWndPhotoWB_Menu_Setting;

#endif
