//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPHOTOCOLOR_H
#define UIMENUWNDPHOTOCOLOR_H

#include "UIFramework.h"

extern VControl UIMenuWndPhotoColorCtrl;//Panel type

extern VControl UIMenuWndPhotoColor_PanelCtrl;//Panel type

extern VControl UIMenuWndPhotoColor_MenuCtrl;//Menu type

typedef enum {
	UIMenuWndPhotoColor_Menu_STRID_COLOR,
	UIMenuWndPhotoColor_Menu_STRID_COLOR_BW,
	UIMenuWndPhotoColor_Menu_STRID_COLOR_SEPIA,
	UIMenuWndPhotoColor_Menu_MAX
} UIMenuWndPhotoColor_Menu_Setting;

#endif
