#include <stdio.h>
#include "Debug.h"
#include "PrjCfg.h"
#include "UIAppMovie_Param.h"
#if(IPCAM_FUNC==ENABLE)
#include "ImageApp_IPCam.h"
#endif
#include "ImageUnit_AudEnc.h"
#include "Audio.h"
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIAppMovieParam
#define __DBGLVL__          6 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"
///////////////////////////////////////////////////////////////////////////////

////for testing, will kill in the future
#if (SENSOR_CAPS_COUNT == 4)
#define FOUR_SENSOR         ENABLE
#else
#define FOUR_SENSOR         DISABLE
#endif

#define TEST_510_64MB       DISABLE
///end for testing


#if(IPCAM_FUNC==ENABLE)

#if(FOUR_SENSOR == ENABLE)
static IPCAM_STREAM_INFO g_ImageAppStreamInfo[IPCAM_PATH_MAX_ID] = {
	{IPCAM_PATH_ID_0, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_1, IPCAM_STATE_ENABLE, IPCAM_SENSOR2, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_2, IPCAM_STATE_ENABLE, IPCAM_SENSOR3, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_3, IPCAM_STATE_ENABLE, IPCAM_SENSOR4, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_4, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_5, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_6, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_7, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_8, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_9, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_10, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_11, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_12, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_13, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_14, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_15, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME5, IPCAM_STREAM_EXT}
};

static UIAPPMOVIE_SENSOR_INFO g_UIAppMovieSensorInfo[UIAPPMOVIE_SENSOR_MAX] = {
	//sensor ID,  IPL fps, IPL ratio, flip type, IME 3DNR , video format[ime_out], video compress
	{UIAPPMOVIE_SENSOR1, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR2, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR3, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR4, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR5, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR6, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR7, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR8, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE}
};

static UIAPPMOVIE_ENCODE_CONFIG g_UIAppMovieEncodeConfig[UIAPPMOVIE_PATH_MAX_ID] = {
	//ID             ,fps, size       , bitrate (byte) ,   codec         ,encode 3DNR
	{UIAPPMOVIE_PATH_ID_0, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_1, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_2, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_3, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_4, 30, {640, 480},       1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_5, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_6, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_7, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_8, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_9, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_10, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_11, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_12, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_13, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_14, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_15, 30, {640, 480},      1 * 1024 * 1024, MEDIAVIDENC_H264, -1}
};

#elif(TEST_510_64MB == ENABLE)

static IPCAM_STREAM_INFO g_ImageAppStreamInfo[IPCAM_PATH_MAX_ID] = {
	{IPCAM_PATH_ID_0, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_1, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_2, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME3, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_3, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_4, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_5, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_6, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_7, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_8, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_9, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_10, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_11, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_12, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_13, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_14, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_15, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME5, IPCAM_STREAM_EXT}
};

static UIAPPMOVIE_SENSOR_INFO g_UIAppMovieSensorInfo[UIAPPMOVIE_SENSOR_MAX] = {

	//sensor ID,  IPL fps, IPL ratio, flip type, IME 3DNR , video format[ime_out], video compress
	{UIAPPMOVIE_SENSOR1, 30, {16, 9}, FLIP_NONE, TRUE,   {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR2, 30, {4, 3}, FLIP_NONE, FALSE,   {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR3, 30, {16, 9}, FLIP_NONE, TRUE,   {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR4, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR5, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR6, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR7, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR8, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE}
};


static UIAPPMOVIE_ENCODE_CONFIG g_UIAppMovieEncodeConfig[UIAPPMOVIE_PATH_MAX_ID] = {
	//ID             ,fps, size       , bitrate (byte) ,   codec         ,encode 3DNR
	{UIAPPMOVIE_PATH_ID_0, 30, {1920, 1080},     256 * 1024, MEDIAVIDENC_H265, 0},
	{UIAPPMOVIE_PATH_ID_1, 30, {720, 576},       100 * 1024, MEDIAVIDENC_H265, -1},
	{UIAPPMOVIE_PATH_ID_2, 30, {640, 480},       100 * 1024, MEDIAVIDENC_H265, 0},
	{UIAPPMOVIE_PATH_ID_3, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_4, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_5, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_6, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_7, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_8, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_9, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_10, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_11, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_12, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_13, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_14, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_15, 30, {640, 480},      1 * 1024 * 1024, MEDIAVIDENC_H264, -1}
};
#else

static IPCAM_STREAM_INFO g_ImageAppStreamInfo[UIAPPMOVIE_PATH_MAX_ID] = {
	{IPCAM_PATH_ID_0, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_1, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_2, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME3, IPCAM_STREAM_MAIN},
	{IPCAM_PATH_ID_3, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME5, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_4, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_5, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_6, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_7, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_8, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_9, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_10, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_11, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_12, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_13, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_14, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT},
	{IPCAM_PATH_ID_15, IPCAM_STATE_ENABLE, IPCAM_SENSOR1, IPCAM_IME5, IPCAM_STREAM_MAIN}
};

static UIAPPMOVIE_SENSOR_INFO g_UIAppMovieSensorInfo[UIAPPMOVIE_SENSOR_MAX] = {
	//sensor ID,  IPL fps, IPL ratio, flip type, IME 3DNR , video format[ime_out], video compress
	{UIAPPMOVIE_SENSOR1, 30, {16, 9}, FLIP_NONE, TRUE,   {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR2, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR3, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR4, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR5, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR6, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR7, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE},
	{UIAPPMOVIE_SENSOR8, 30, {16, 9}, FLIP_NONE, FALSE,  {GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_YUV420, GX_IMAGE_PIXEL_FMT_Y_ONLY, GX_IMAGE_PIXEL_FMT_YUV422}, FALSE}
};


static UIAPPMOVIE_ENCODE_CONFIG g_UIAppMovieEncodeConfig[UIAPPMOVIE_PATH_MAX_ID] = {
	//ID             ,fps, size       , bitrate (byte) ,   codec         ,encode 3DNR
	{UIAPPMOVIE_PATH_ID_0, 30, {3840, 2160},     3 * 1024 * 1024, MEDIAVIDENC_H264, 0},
	{UIAPPMOVIE_PATH_ID_1, 30, {1920, 1080},     1 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_2, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_3, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_4, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_5, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_6, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_7, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_8, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_9, 30, {1920, 1080},     3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_10, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_11, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_12, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_13, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_14, 30, {1920, 1080},    3 * 1024 * 1024, MEDIAVIDENC_H264, -1},
	{UIAPPMOVIE_PATH_ID_15, 30, {640, 480},      1 * 1024 * 1024, MEDIAVIDENC_H264, -1}
};
#endif


static UIAPPMOVIE_AUDIO_INFO    g_AudioInfo = { ISF_AUDENC_ENCODER_PCM, AUDIO_CH_LEFT, AUDIO_SR_48000, 100 };
static UIAPPMOVIE_AUDIO_INFO    g_AudioOutInfo = { ISF_AUDENC_ENCODER_PCM, AUDIO_CH_RIGHT, AUDIO_SR_48000, 100 };





void *ImageApp_get_streamInfo(void)
{

	return &g_ImageAppStreamInfo[0];
}

void ImageApp_set_StreamInfo(void *streamInfo)
{
	DBG_FUNC_BEGIN("\r\n");
	if (streamInfo != NULL) {
		memcpy(g_ImageAppStreamInfo, streamInfo, sizeof(g_ImageAppStreamInfo));
#if(IPCAM_FUNC == ENABLE)
		ImageApp_IPCam_set_StreamInfo(&g_ImageAppStreamInfo[0]);
#endif
	} else {
		DBG_ERR("streamInfo is null\r\n");
	}
	DBG_FUNC_END("\r\n");

}



UIAPPMOVIE_AUDIO_INFO *UIAppMovie_get_AudioInfo(void)
{

	return &g_AudioInfo;

}

void UIAppMovie_set_AudioInfo(UIAPPMOVIE_AUDIO_INFO *pAudioInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pAudioInfo != NULL) {
		memcpy(&g_AudioInfo, pAudioInfo, sizeof(UIAPPMOVIE_AUDIO_INFO));
	} else {
		DBG_ERR("pAudioInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}

UIAPPMOVIE_AUDIO_INFO *UIAppMovie_get_AudioOutInfo(void)
{

	return &g_AudioOutInfo;

}

void UIAppMovie_set_AudioOutInfo(UIAPPMOVIE_AUDIO_INFO *pAudioOutInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pAudioOutInfo != NULL) {
		memcpy(&g_AudioOutInfo, pAudioOutInfo, sizeof(UIAPPMOVIE_AUDIO_INFO));
	} else {
		DBG_ERR("pAudioOutInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}


void UIAppMovie_set_SensorInfo(UIAPPMOVIE_SENSOR_INFO *SensorInfo)
{
	DBG_FUNC_BEGIN("\r\n");
	if (SensorInfo != NULL) {
		memcpy(g_UIAppMovieSensorInfo, SensorInfo, sizeof(UIAPPMOVIE_SENSOR_INFO));
	} else {
		DBG_ERR("sensorInfo is null\r\n");
	}
	DBG_FUNC_END("\r\n");
}
UIAPPMOVIE_SENSOR_INFO *UIAppMovie_get_SensorInfo(void)
{

	return &g_UIAppMovieSensorInfo[0];
}

UIAPPMOVIE_ENCODE_CONFIG *UIAppMovie_get_EncodeConfig(void)
{

	return &g_UIAppMovieEncodeConfig[0];

}

void UIAppMovie_set_EncodeConfig(UIAPPMOVIE_ENCODE_CONFIG *EncodeConfig)
{
	DBG_FUNC_BEGIN("\r\n");
	if (EncodeConfig != NULL) {
		memcpy(g_UIAppMovieEncodeConfig, EncodeConfig, sizeof(UIAPPMOVIE_ENCODE_CONFIG));
	} else {
		DBG_ERR("EncodeConfig is null\r\n");
	}
	DBG_FUNC_END("\r\n");
}





void UIAppMovie_set_DisplayPath(INT32 path)
{
	////if path == -1 , means close display path
	if (path < -1 || path > UIAPPMOVIE_PATH_ID_15) {
		DBG_ERR("set display path error, path =%d\r\n", path);
		return;
	}
#if(IPCAM_FUNC == ENABLE)
#if(FOUR_SENSOR == ENABLE)
	static UINT32 first_run = 0;
	if (first_run == 0) {
		first_run++;
		path = 0;
	}
#endif
#if(TEST_510_64MB == ENABLE)
	path = 1;
#endif
	ImageApp_IPCam_Config(IPCAM_DISP_PATH, path);
#else
	DBG_WRN("not support!!\r\n");
#endif
}


INT32 UIAppMovie_get_DisplayPath(void)
{

#if(IPCAM_FUNC == ENABLE)
	return ImageApp_IPCam_GetConfig(IPCAM_DISP_PATH);

#else
	DBG_WRN("not support!!\r\n");
	return -1;
#endif
}

INT32 UIAppMovie_get_ALGPath(void)
{

#if(IPCAM_FUNC == ENABLE)
	return ImageApp_IPCam_GetConfig(IPCAM_ALG_PATH);

#else
	DBG_WRN("not support!!\r\n");
	return -1;
#endif
}

void UIAppMovie_set_ALGPath(INT32 path)
{
	////if path == -1 , means close ALG path
	if (path < -1 || path > UIAPPMOVIE_PATH_ID_15) {
		DBG_ERR("set display path error, path =%d\r\n", path);
		return;
	}
#if(IPCAM_FUNC == ENABLE)
#if(FOUR_SENSOR == ENABLE)
	path = -1;
#elif(TEST_510_64MB == ENABLE)
	path = -1;
#endif
	ImageApp_IPCam_Config(IPCAM_ALG_PATH, path);
#else
	DBG_WRN("not support!!\r\n");
#endif
}

#endif
