#
# (C) Copyright 2017
# Novatek Microelectronic corp.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_NVT_SPI_NOR) += nor-680.o
ifdef CONFIG_CMD_NAND
obj-$(CONFIG_NVT_SPI_NAND) += nand-680.o
endif
