#
# Makefile for NVT processors family
#

obj-$(CONFIG_MACH_NVT_NA51000)	+= board-dt.o io.o reset.o

obj-$(CONFIG_NVT_INFO)		+= nvt-info.o

obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o

obj-$(CONFIG_HOTPLUG_CPU)	+= hotplug.o

obj-$(CONFIG_PM)		+= pm.o sleep.o
