//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDUSB_H
#define UIMENUWNDUSB_H

#include "UIFramework.h"

extern VControl UIMenuWndUSBCtrl;//Panel type

extern VControl UIMenuWndUSB_BackgroundCtrl;//Panel type

extern VControl UIMenuWndUSB_TitleBarCtrl;//Panel type

extern VControl UIMenuWndUSB_TitleNameCtrl;//Status type

typedef enum {
	UIMenuWndUSB_TitleName_STRID_USB,
	UIMenuWndUSB_TitleName_MAX
} UIMenuWndUSB_TitleName_Setting;

extern VControl UIMenuWndUSB_ItemCtrl;//Menu type

typedef enum {
	UIMenuWndUSB_Item_STRID_MSDC,
	UIMenuWndUSB_Item_STRID_PCC,
	UIMenuWndUSB_Item_MAX
} UIMenuWndUSB_Item_Setting;

extern VControl MenuCommItem_PanelUSBCtrl;//Panel type

extern VControl MenuCommonItem_LeftUSBCtrl;//Static type

extern VControl MenuCommonItem_RightUSBCtrl;//Static type

extern VControl MenuCommonItem_LeftIconUSBCtrl;//Static type

extern VControl MenuCommonItem_RightIconUSBCtrl;//Static type

//---------------------UIMenuWndUSBCtrl User Export---------------------------
#endif
