//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndUSBRes.c"
#include "UIMenuWndUSB.h"
#include "AppControl.h"
#include "SysCommon.h"
#include "UICommon.h"

//---------------------UIMenuWndUSBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB)
CTRL_LIST_ITEM(UIMenuWndUSB_Background)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_Item)
#if defined(_KEY_METHOD_2KEY_)
CTRL_LIST_ITEM(MenuCommItem_PanelUSB)
#endif
CTRL_LIST_END

//----------------------UIMenuWndUSBCtrl Event---------------------------
INT32 UIMenuWndUSB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_OnChildClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndUSB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndUSB_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, UIMenuWndUSB_OnChildClose)
EVENT_END

INT32 UIMenuWndUSB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
//---------------------UIMenuWndUSB_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_Background)
CTRL_LIST_END

//----------------------UIMenuWndUSB_BackgroundCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_Background)
EVENT_END

//---------------------UIMenuWndUSB_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndUSB_TitleBar)
CTRL_LIST_ITEM(UIMenuWndUSB_TitleName)
CTRL_LIST_END

//----------------------UIMenuWndUSB_TitleBarCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleBar)
EVENT_END

//----------------------UIMenuWndUSB_TitleNameCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndUSB_TitleName)
EVENT_END

//----------------------UIMenuWndUSB_ItemCtrl Event---------------------------
INT32 UIMenuWndUSB_Item_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndUSB_Item_OnKeySelect(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndUSB_Item)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIMenuWndUSB_Item_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIMenuWndUSB_Item_OnKeySelect)
EVENT_END

INT32 UIMenuWndUSB_Item_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndUSB_Item_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  item;

	item = UxMenu_GetData(pCtrl, MNU_CURITM);
	if (item == UIMenuWndUSB_Item_STRID_MSDC) {
		Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_USBMSDC);
	} else if (item == UIMenuWndUSB_Item_STRID_PCC) {
		Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_USBPCC);
	}
	return NVTEVT_CONSUME;
}
//---------------------MenuCommItem_PanelUSBCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommItem_PanelUSB)
CTRL_LIST_ITEM(MenuCommonItem_LeftUSB)
CTRL_LIST_ITEM(MenuCommonItem_RightUSB)
CTRL_LIST_ITEM(MenuCommonItem_LeftIconUSB)
CTRL_LIST_ITEM(MenuCommonItem_RightIconUSB)
CTRL_LIST_END

//----------------------MenuCommItem_PanelUSBCtrl Event---------------------------
EVENT_BEGIN(MenuCommItem_PanelUSB)
EVENT_END

//----------------------MenuCommonItem_LeftUSBCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_LeftUSB)
EVENT_END

//----------------------MenuCommonItem_RightUSBCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_RightUSB)
EVENT_END

//----------------------MenuCommonItem_LeftIconUSBCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_LeftIconUSB)
EVENT_END

//----------------------MenuCommonItem_RightIconUSBCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_RightIconUSB)
EVENT_END

