/*
 * Copyright (C) 2012 Novatek Microelectronics Corp. All Rights Reserved.
 *
 * Configuration settings for the board.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __NAND_PARTITION_LAYOUT_H__
#define __NAND_PARTITION_LAYOUT_H__

typedef enum {
        NVT_FLASH_UPDATE_ONBOOT = '0',
        NVT_FLASH_UPDATE_UBOOT = '1',
		NVT_FLASH_UPDATE_DT = '2',
        NVT_FLASH_UPDATE_KERNEL = '3',
        NVT_FLASH_UPDATE_ROOTFS = '4',
		NVT_FLASH_UPDATE_SERET = '5',
		NVT_FLASH_UPDATE_SIGN = '6',
		NVT_FLASH_UPDATE_SECOS = '7',
		NVT_FLASH_UPDATE_ERASE_ALL = '8',
		NVT_FLASH_UPDATE_SHOW_MENU = 'M',
		NVT_FLASH_UPDATE_EXIT = 'F'
} NAND_UPDATE_COMMAND_TYPE;

typedef struct NVT_UPDATE_PARAMETER
{
   unsigned long ulSourceBuffer;
   unsigned long ulSourceLen;
   unsigned long ulFlashAddr;
   unsigned long ulFlashSpace;
   unsigned char ucImageFileName[40];
}NVT_UPDATE_PARAMETER, *PNVT_UPDATE_PARAMETER;

#define CONFIG_NAND
#define CONFIG_CMD_NAND
#define CONFIG_SYS_MAX_NAND_DEVICE	1

//************************ Buffer list for uboot update ***************************
#define NVT_FLASH_UPDATE_BUFFER_ADDR         0x28000000
#define NVT_FLASH_UPDATE_VERIFY_BUFFER_ADDR  0x29000000

#define NVT_NAND_ONBOOT_SOURCE_ADDR    NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_UBOOT_SOURCE_ADDR     NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_KERNEL_SOURCE_ADDR    NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_ROOTFS_SOURCE_ADDR    NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_SERET_SOURCE_ADDR     NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_SIGN_SOURCE_ADDR      NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_SECOS_SOURCE_ADDR     NVT_FLASH_UPDATE_BUFFER_ADDR
#define NVT_NAND_DT_SOURCE_ADDR     NVT_FLASH_UPDATE_BUFFER_ADDR



//************************** NAND flash memory layout ****************************
#define KERNEL_HEADER_SIGN_LEN 0

#define KERNEL_BUFFER_HEADER_BLOCK     (0xA0800000 - 64 - KERNEL_HEADER_SIGN_LEN) /* 1st block (128kb) */
#define KERNEL_BUFFER_IMAGE_BLOCK      (0xA0120000 - 64 - KERNEL_HEADER_SIGN_LEN) /* 2nd block ~~~  */
#define KERNEL_BUFFER_IMAGE_ADDR       (0x80100000)

//Size of each image
#define NVT_NAND_ONBOOT_DEFAULT_SIZE    0x20000
#define NVT_NAND_UBOOT_DEFAULT_SIZE     0x80000
#define NVT_NAND_KERNEL_DEFAULT_SIZE    0x700000
#define NVT_NAND_ROOTFS_DEFAULT_SIZE    0x1600000
#define NVT_NAND_SERET_DEFAULT_SIZE     0x80000
#define NVT_NAND_SIGN_DEFAULT_SIZE      0x20000
#define NVT_NAND_SECOS_DEFAULT_SIZE     0x100000
#define NVT_NAND_DT_DEFAULT_SIZE        0x20000

#define NVT_NAND_UBOOT2_DEFAULT_SIZE    0x80000
#define NVT_NAND_KERNEL2_DEFAULT_SIZE   0x700000
#define NVT_NAND_ROOTFS2_DEFAULT_SIZE   0x1600000
#define NVT_NAND_SERET2_DEFAULT_SIZE    0x80000
#define NVT_NAND_SIGN2_DEFAULT_SIZE     0x20000
#define NVT_NAND_SECOS2_DEFAULT_SIZE    0x100000
#define NVT_NAND_DT2_DEFAULT_SIZE       0x20000

//Reserved size for each partition
#define NVT_NAND_ONBOOT_AVAILABLE_SIZE  0x40000
#define NVT_NAND_UBOOT_AVAILABLE_SIZE   0x100000
#define NVT_NAND_DT_AVAILABLE_SIZE      0x40000
#define NVT_NAND_KERNEL_AVAILABLE_SIZE  0x800000
#define NVT_NAND_ROOTFS_AVAILABLE_SIZE  0x1700000
#define NVT_NAND_SERET_AVAILABLE_SIZE   0x100000
#define NVT_NAND_SIGN_AVAILABLE_SIZE    0x40000
#define NVT_NAND_SECOS_AVAILABLE_SIZE   0x140000

#define NVT_NAND_UBOOT2_AVAILABLE_SIZE  0x100000
#define NVT_NAND_DT2_AVAILABLE_SIZE     0x40000
#define NVT_NAND_KERNEL2_AVAILABLE_SIZE 0x800000
#define NVT_NAND_ROOTFS2_AVAILABLE_SIZE 0x1700000
#define NVT_NAND_SERET2_AVAILABLE_SIZE  0x100000
#define NVT_NAND_SIGN2_AVAILABLE_SIZE   0x40000
#define NVT_NAND_SECOS2_AVAILABLE_SIZE  0x140000

//Starting address for each partition
#define NVT_NAND_ONBOOT_FLASH_ADDR      0
#define NVT_NAND_UBOOT_FLASH_ADDR      (NVT_NAND_ONBOOT_FLASH_ADDR + NVT_NAND_ONBOOT_AVAILABLE_SIZE)
#define NVT_NAND_SERET_FLASH_ADDR      (NVT_NAND_ONBOOT_FLASH_ADDR + NVT_NAND_ONBOOT_AVAILABLE_SIZE) /*The same starting address as UBOOT*/
#define NVT_NAND_DT_FLASH_ADDR         (NVT_NAND_UBOOT_FLASH_ADDR + NVT_NAND_UBOOT_AVAILABLE_SIZE)
#define NVT_NAND_KERNEL_FLASH_ADDR     (NVT_NAND_DT_FLASH_ADDR + NVT_NAND_DT_AVAILABLE_SIZE)
#define NVT_NAND_ROOTFS_FLASH_ADDR     (NVT_NAND_KERNEL_FLASH_ADDR + NVT_NAND_KERNEL_AVAILABLE_SIZE)
#define NVT_NAND_SIGN_FLASH_ADDR       (NVT_NAND_SERET_FLASH_ADDR + NVT_NAND_SERET_DEFAULT_SIZE)
#define NVT_NAND_SECOS_FLASH_ADDR      (NVT_NAND_SIGN_FLASH_ADDR + NVT_NAND_SIGN_DEFAULT_SIZE)

#define NVT_NAND_UBOOT2_FLASH_ADDR     (NVT_NAND_SECOS_FLASH_ADDR + NVT_NAND_SECOS_AVAILABLE_SIZE)  
#define NVT_NAND_SERET2_FLASH_ADDR     (NVT_NAND_SECOS_FLASH_ADDR + NVT_NAND_SECOS_AVAILABLE_SIZE) /*The same starting address as UBOOT2*/
#define NVT_NAND_DT2_FLASH_ADDR        (NVT_NAND_UBOOT_FLASH_ADDR + NVT_NAND_UBOOT_AVAILABLE_SIZE)
#define NVT_NAND_KERNEL2_FLASH_ADDR    (NVT_NAND_DT2_FLASH_ADDR + NVT_NAND_DT2_AVAILABLE_SIZE)
#define NVT_NAND_ROOTFS2_FLASH_ADDR    (NVT_NAND_KERNEL2_FLASH_ADDR + NVT_NAND_KERNEL2_AVAILABLE_SIZE)
#define NVT_NAND_SIGN2_FLASH_ADDR      (NVT_NAND_SERET2_FLASH_ADDR + NVT_NAND_SERET2_DEFAULT_SIZE)
#define NVT_NAND_SECOS2_FLASH_ADDR     (NVT_NAND_SIGN2_FLASH_ADDR + NVT_NAND_SIGN2_DEFAULT_SIZE)

//Image name 
#define NVT_NAND_ONBOOT_FILE_NAME  "update14M/xboot.bin"
#define NVT_NAND_UBOOT_FILE_NAME   "update14M/u-boot.bin"
#define NVT_NAND_KERNEL_FILE_NAME  "update14M/uImage"
#define NVT_NAND_ROOTFS_FILE_NAME  "update14M/rootfs.img"
#define NVT_NAND_SERET_FILE_NAME   "update14M/seret.bin"
#define NVT_NAND_SIGN_FILE_NAME    "update14M/sign.bin"
#define NVT_NAND_SECOS_FILE_NAME   "update14M/secos.bin"
#define NVT_NAND_DT_FILE_NAME      "update14M/nvtca9-72668.dtb"

#define CONFIG_CMD_UPDATE          1
#define ONE_SIGNATURE_SIZE         (1024)

                                                             //Source buffer,            image size                       Flash offset         Total available size          File Name        
static NVT_UPDATE_PARAMETER NVT_update_parameter_table[]  = {{NVT_NAND_ONBOOT_SOURCE_ADDR, NVT_NAND_ONBOOT_DEFAULT_SIZE, NVT_NAND_ONBOOT_FLASH_ADDR, NVT_NAND_ONBOOT_AVAILABLE_SIZE, NVT_NAND_ONBOOT_FILE_NAME},
                   											  {NVT_NAND_UBOOT_SOURCE_ADDR, NVT_NAND_UBOOT_DEFAULT_SIZE, NVT_NAND_UBOOT_FLASH_ADDR, NVT_NAND_UBOOT_AVAILABLE_SIZE, NVT_NAND_UBOOT_FILE_NAME},
              				   								  {NVT_NAND_DT_SOURCE_ADDR, NVT_NAND_DT_DEFAULT_SIZE, NVT_NAND_DT_FLASH_ADDR, NVT_NAND_DT_AVAILABLE_SIZE, NVT_NAND_DT_FILE_NAME},
															  {NVT_NAND_KERNEL_SOURCE_ADDR, NVT_NAND_KERNEL_DEFAULT_SIZE, NVT_NAND_KERNEL_FLASH_ADDR, NVT_NAND_KERNEL_AVAILABLE_SIZE, NVT_NAND_KERNEL_FILE_NAME},
				          									  {NVT_NAND_ROOTFS_SOURCE_ADDR, NVT_NAND_ROOTFS_DEFAULT_SIZE, NVT_NAND_ROOTFS_FLASH_ADDR, NVT_NAND_ROOTFS_AVAILABLE_SIZE, NVT_NAND_ROOTFS_FILE_NAME},
															  {NVT_NAND_SERET_SOURCE_ADDR, NVT_NAND_SERET_DEFAULT_SIZE, NVT_NAND_SERET_FLASH_ADDR, NVT_NAND_SERET_AVAILABLE_SIZE, NVT_NAND_SERET_FILE_NAME},
  															  {NVT_NAND_SIGN_SOURCE_ADDR, NVT_NAND_SIGN_DEFAULT_SIZE, NVT_NAND_SIGN_FLASH_ADDR, NVT_NAND_SIGN_AVAILABLE_SIZE, NVT_NAND_SIGN_FILE_NAME},
															  {NVT_NAND_SECOS_SOURCE_ADDR, NVT_NAND_SECOS_DEFAULT_SIZE, NVT_NAND_SECOS_FLASH_ADDR, NVT_NAND_SECOS_AVAILABLE_SIZE, NVT_NAND_SECOS_FILE_NAME}};


#endif
