#!/bin/sh

NETWORK_SETUP_SCRIPT="/etc/init.d/net_init.sh"

echo "eth" > /proc/nvt_info/bootts
modprobe ntkimethmac

#FOR NVTIMETHMAC
ifconfig eth0 down
ifconfig eth0 hw ether 00:80:48:BA:D1:30
ifconfig eth0 up

if [ -f "$NETWORK_SETUP_SCRIPT" ]; then
    $NETWORK_SETUP_SCRIPT
else
    echo "Configuring loopback interface"
    ifconfig lo 127.0.0.1

    ifconfig eth0 192.168.0.3

    #FOR WiFi Sample
    # ifup wlan0
    # hostapd -B -dd /etc/wifiap_wpa2.conf

    #DHCP Deamon
    udhcpd -fS /etc/udhcpd.conf &

    #FTP
    #inetd &
fi

echo "eth" > /proc/nvt_info/bootts

uctrl usys -notify net_init_ok
