/**
	NVT IOCFG driver
	To handle NVT IOCFG driver
	@ingroup
	@note
	Copyright Novatek Microelectronics Corp. 2016. All rights reserved.

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License version 2 as
	published by the Free Software Foundation.
*/
#ifndef _IOCFG_INT_H
#define _IOCFG_INT_H

#include <asm/arch/rcw_macro.h>
#include <asm/arch/IOAddress.h>

#define GPIO_GETREG(ofs)	INW(IOADDR_GPIO_REG_BASE+(ofs))
#define GPIO_SETREG(ofs, value)	OUTW(IOADDR_GPIO_REG_BASE +(ofs),(value))
#define PAD_GETREG(ofs)		INW(IOADDR_PAD_REG_BASE+(ofs))
#define PAD_SETREG(ofs, value)	OUTW(IOADDR_PAD_REG_BASE +(ofs),(value))

#define GPIO_SET_OUTPUT_HI      0x1
#define PAD_PUPD0_REG_OFS	0x00
#define GPIO_STRG_DIR_REG_OFS	0x30
#define GPIO_STRG_SET0_REG_OFS	0x50
#define GPIO_STRG_CLR0_REG_OFS	0x70

typedef enum {
	GPIO_DIR_INPUT =            0,      ///< GPIO is input direction
	GPIO_DIR_OUTPUT =           1,      ///< GPIO is output direction

	ENUM_DUMMY4WORD(GPIO_DIR)
} GPIO_DIR;

typedef enum {
	PAD_NONE         =          0x00,      ///< none of pull up/down
	PAD_PULLDOWN     =          0x01,      ///< pull down
	PAD_PULLUP       =          0x02,      ///< pull up
	PAD_KEEPER       =          0x03,      ///< keeper

	ENUM_DUMMY4WORD(PAD_PULL)
} PAD_PULL;

struct pad_pullupdown_pin {
	u16 pin;
	u8 pup;
	u8 bit_ofs;
};
#define PAD_PIN_NOT_EXIST	(15)                        // For backward compatible
//@{
//CGPIOx group begin
#define PAD_PIN_CGPIO_BASE	0
#define PAD_PIN_CGPIO0	(PAD_PIN_CGPIO_BASE + 0)	///< CGPIO0
#define PAD_PIN_CGPIO1	(PAD_PIN_CGPIO_BASE + 1)	///< CGPIO1
#define PAD_PIN_CGPIO2	(PAD_PIN_CGPIO_BASE + 2)	///< CGPIO2
#define PAD_PIN_CGPIO3	(PAD_PIN_CGPIO_BASE + 3)	///< CGPIO3
#define PAD_PIN_CGPIO4	(PAD_PIN_CGPIO_BASE + 4)	///< CGPIO4
#define PAD_PIN_CGPIO5	(PAD_PIN_CGPIO_BASE + 5)	///< CGPIO5
#define PAD_PIN_CGPIO6	(PAD_PIN_CGPIO_BASE + 6)	///< CGPIO6
#define PAD_PIN_CGPIO7	(PAD_PIN_CGPIO_BASE + 7)	///< CGPIO7
#define PAD_PIN_CGPIO8	(PAD_PIN_CGPIO_BASE + 8)	///< CGPIO8
#define PAD_PIN_CGPIO9	(PAD_PIN_CGPIO_BASE + 9)	///< CGPIO9
#define PAD_PIN_CGPIO10	(PAD_PIN_CGPIO_BASE + 10)	///< CGPIO10
#define PAD_PIN_CGPIO11	(PAD_PIN_CGPIO_BASE + 11)	///< CGPIO11
#define PAD_PIN_CGPIO12	(PAD_PIN_CGPIO_BASE + 12)	///< CGPIO12
#define PAD_PIN_CGPIO13	(PAD_PIN_CGPIO_BASE + 13)	///< CGPIO13
#define PAD_PIN_CGPIO14	(PAD_PIN_CGPIO_BASE + 14)	///< CGPIO14
#define PAD_PIN_CGPIO15	(PAD_PIN_CGPIO_BASE + 15)	///< CGPIO15

#define PAD_PIN_CGPIO16	(PAD_PIN_CGPIO_BASE + 16)	///< CGPIO16
#define PAD_PIN_CGPIO17	(PAD_PIN_CGPIO_BASE + 17)	///< CGPIO17
#define PAD_PIN_CGPIO18	(PAD_PIN_CGPIO_BASE + 18)	///< CGPIO18
#define PAD_PIN_CGPIO19	(PAD_PIN_CGPIO_BASE + 19)	///< CGPIO19
#define PAD_PIN_CGPIO20	(PAD_PIN_CGPIO_BASE + 20)	///< CGPIO20
#define PAD_PIN_CGPIO21	(PAD_PIN_CGPIO_BASE + 21)	///< CGPIO21
#define PAD_PIN_CGPIO22	(PAD_PIN_CGPIO_BASE + 22)	///< CGPIO22
#define PAD_PIN_CGPIO23	(PAD_PIN_CGPIO_BASE + 23)	///< CGPIO23
#define PAD_PIN_CGPIO24	(PAD_PIN_CGPIO_BASE + 24)	///< CGPIO24
#define PAD_PIN_CGPIO25	(PAD_PIN_CGPIO_BASE + 25)	///< CGPIO25
#define PAD_PIN_CGPIO26	(PAD_PIN_CGPIO_BASE + 26)	///< CGPIO26
#define PAD_PIN_CGPIO27	(PAD_PIN_CGPIO_BASE + 27)	///< CGPIO27
#define PAD_PIN_CGPIO28	(PAD_PIN_CGPIO_BASE + 28)	///< CGPIO28
#define PAD_PIN_CGPIO29	(PAD_PIN_CGPIO_BASE + 29)	///< CGPIO29
#define PAD_PIN_CGPIO30	(PAD_PIN_CGPIO_BASE + 30)	///< CGPIO30
#define PAD_PIN_CGPIO31	(PAD_PIN_CGPIO_BASE + 31)	///< CGPIO31

#define PAD_PIN_CGPIO32	(PAD_PIN_CGPIO_BASE + 32)	///< CGPIO32
#define PAD_PIN_CGPIO33	(PAD_PIN_CGPIO_BASE + 33)	///< CGPIO33
//CGPIOx group end

//SGPIOx group begin
#define PAD_PIN_SGPIO_BASE	100
#define PAD_PIN_SGPIO0	(PAD_PIN_SGPIO_BASE + 0)	///< SGPIO0
#define PAD_PIN_SGPIO1	(PAD_PIN_SGPIO_BASE + 1)	///< SGPIO1
#define PAD_PIN_SGPIO2	(PAD_PIN_SGPIO_BASE + 2)	///< SGPIO2
#define PAD_PIN_SGPIO3	(PAD_PIN_SGPIO_BASE + 3)	///< SGPIO3
#define PAD_PIN_SGPIO4	(PAD_PIN_SGPIO_BASE + 4)	///< SGPIO4
#define PAD_PIN_SGPIO5	(PAD_PIN_SGPIO_BASE + 5)	///< SGPIO5
#define PAD_PIN_SGPIO6	(PAD_PIN_SGPIO_BASE + 6)	///< SGPIO6
#define PAD_PIN_SGPIO7	(PAD_PIN_SGPIO_BASE + 7)	///< SGPIO7
#define PAD_PIN_SGPIO8	(PAD_PIN_SGPIO_BASE + 8)	///< SGPIO8
#define PAD_PIN_SGPIO9	(PAD_PIN_SGPIO_BASE + 9)	///< SGPIO9
#define PAD_PIN_SGPIO10	(PAD_PIN_SGPIO_BASE + 10)	///< SGPIO10
#define PAD_PIN_SGPIO11	(PAD_PIN_SGPIO_BASE + 11)	///< SGPIO11
//SGPIOx group end

//PGPIOx group begin
#define PAD_PIN_PGPIO_BASE	150
#define PAD_PIN_PGPIO0	(PAD_PIN_PGPIO_BASE + 0)	///< PGPIO0
#define PAD_PIN_PGPIO1	(PAD_PIN_PGPIO_BASE + 1)	///< PGPIO1
#define PAD_PIN_PGPIO2	(PAD_PIN_PGPIO_BASE + 2)	///< PGPIO2
#define PAD_PIN_PGPIO3	(PAD_PIN_PGPIO_BASE + 3)	///< PGPIO3
#define PAD_PIN_PGPIO4	(PAD_PIN_PGPIO_BASE + 4)	///< PGPIO4
#define PAD_PIN_PGPIO5	(PAD_PIN_PGPIO_BASE + 5)	///< PGPIO5
#define PAD_PIN_PGPIO6	(PAD_PIN_PGPIO_BASE + 6)	///< PGPIO6
#define PAD_PIN_PGPIO7	(PAD_PIN_PGPIO_BASE + 7)	///< PGPIO7
#define PAD_PIN_PGPIO8	(PAD_PIN_PGPIO_BASE + 8)	///< PGPIO8
#define PAD_PIN_PGPIO9	(PAD_PIN_PGPIO_BASE + 9)	///< PGPIO9
#define PAD_PIN_PGPIO10	(PAD_PIN_PGPIO_BASE + 10)	///< PGPIO10
#define PAD_PIN_PGPIO11	(PAD_PIN_PGPIO_BASE + 11)	///< PGPIO11
#define PAD_PIN_PGPIO12	(PAD_PIN_PGPIO_BASE + 12)	///< PGPIO12
#define PAD_PIN_PGPIO13	(PAD_PIN_PGPIO_BASE + 13)	///< PGPIO13
#define PAD_PIN_PGPIO14	(PAD_PIN_PGPIO_BASE + 14)	///< PGPIO14
#define PAD_PIN_PGPIO15	(PAD_PIN_PGPIO_BASE + 15)	///< PGPIO15

#define PAD_PIN_PGPIO16	(PAD_PIN_PGPIO_BASE + 16)	///< PGPIO16
#define PAD_PIN_PGPIO17	(PAD_PIN_PGPIO_BASE + 17)	///< PGPIO17
#define PAD_PIN_PGPIO18	(PAD_PIN_PGPIO_BASE + 18)	///< PGPIO18
#define PAD_PIN_PGPIO19	(PAD_PIN_PGPIO_BASE + 19)	///< PGPIO19
#define PAD_PIN_PGPIO20	(PAD_PIN_PGPIO_BASE + 20)	///< PGPIO20
#define PAD_PIN_PGPIO21	(PAD_PIN_PGPIO_BASE + 21)	///< PGPIO21
#define PAD_PIN_PGPIO22	(PAD_PIN_PGPIO_BASE + 22)	///< PGPIO22
#define PAD_PIN_PGPIO23	(PAD_PIN_PGPIO_BASE + 23)	///< PGPIO23
#define PAD_PIN_PGPIO24	(PAD_PIN_PGPIO_BASE + 24)	///< PGPIO24
#define PAD_PIN_PGPIO25	(PAD_PIN_PGPIO_BASE + 25)	///< PGPIO25
#define PAD_PIN_PGPIO26	(PAD_PIN_PGPIO_BASE + 26)	///< PGPIO26
#define PAD_PIN_PGPIO27	(PAD_PIN_PGPIO_BASE + 27)	///< PGPIO27
#define PAD_PIN_PGPIO28	(PAD_PIN_PGPIO_BASE + 28)	///< PGPIO28
#define PAD_PIN_PGPIO29	(PAD_PIN_PGPIO_BASE + 29)	///< PGPIO29
#define PAD_PIN_PGPIO30	(PAD_PIN_PGPIO_BASE + 30)	///< PGPIO30
#define PAD_PIN_PGPIO31	(PAD_PIN_PGPIO_BASE + 31)	///< PGPIO31

#define PAD_PIN_PGPIO32	(PAD_PIN_PGPIO_BASE + 32)	///< PGPIO32
#define PAD_PIN_PGPIO33	(PAD_PIN_PGPIO_BASE + 33)	///< PGPIO33
#define PAD_PIN_PGPIO34	(PAD_PIN_PGPIO_BASE + 34)	///< PGPIO34
#define PAD_PIN_PGPIO35	(PAD_PIN_PGPIO_BASE + 35)	///< PGPIO35
#define PAD_PIN_PGPIO36	(PAD_PIN_PGPIO_BASE + 36)	///< PGPIO36
#define PAD_PIN_PGPIO37	(PAD_PIN_PGPIO_BASE + 37)	///< PGPIO37
#define PAD_PIN_PGPIO38	(PAD_PIN_PGPIO_BASE + 38)	///< PGPIO38
#define PAD_PIN_PGPIO39	(PAD_PIN_PGPIO_BASE + 39)	///< PGPIO39
#define PAD_PIN_PGPIO40	(PAD_PIN_PGPIO_BASE + 40)	///< PGPIO40
#define PAD_PIN_PGPIO41	(PAD_PIN_PGPIO_BASE + 41)	///< PGPIO41
#define PAD_PIN_PGPIO42	(PAD_PIN_PGPIO_BASE + 42)	///< PGPIO42
#define PAD_PIN_PGPIO43	(PAD_PIN_PGPIO_BASE + 43)	///< PGPIO43
#define PAD_PIN_PGPIO44	(PAD_PIN_PGPIO_BASE + 44)	///< PGPIO44
#define PAD_PIN_PGPIO45	(PAD_PIN_PGPIO_BASE + 45)	///< PGPIO45
#define PAD_PIN_PGPIO46	(PAD_PIN_PGPIO_BASE + 46)	///< PGPIO46
#define PAD_PIN_PGPIO47	(PAD_PIN_PGPIO_BASE + 47)	///< PGPIO47
//PGPIOx group end


//LGPIOx group begin
#define PAD_PIN_LGPIO_BASE	250
#define PAD_PIN_LGPIO0	(PAD_PIN_LGPIO_BASE + 0)	///< LGPIO0
#define PAD_PIN_LGPIO1	(PAD_PIN_LGPIO_BASE + 1)	///< LGPIO1
#define PAD_PIN_LGPIO2	(PAD_PIN_LGPIO_BASE + 2)	///< LGPIO2
#define PAD_PIN_LGPIO3	(PAD_PIN_LGPIO_BASE + 3)	///< LGPIO3
#define PAD_PIN_LGPIO4	(PAD_PIN_LGPIO_BASE + 4)	///< LGPIO4
#define PAD_PIN_LGPIO5	(PAD_PIN_LGPIO_BASE + 5)	///< LGPIO5
#define PAD_PIN_LGPIO6	(PAD_PIN_LGPIO_BASE + 6)	///< LGPIO6
#define PAD_PIN_LGPIO7	(PAD_PIN_LGPIO_BASE + 7)	///< LGPIO7
#define PAD_PIN_LGPIO8	(PAD_PIN_LGPIO_BASE + 8)	///< LGPIO8
#define PAD_PIN_LGPIO9	(PAD_PIN_LGPIO_BASE + 9)	///< LGPIO9
#define PAD_PIN_LGPIO10	(PAD_PIN_LGPIO_BASE + 10)	///< LGPIO10
#define PAD_PIN_LGPIO11	(PAD_PIN_LGPIO_BASE + 11)	///< LGPIO11
#define PAD_PIN_LGPIO12	(PAD_PIN_LGPIO_BASE + 12)	///< LGPIO12
#define PAD_PIN_LGPIO13	(PAD_PIN_LGPIO_BASE + 13)	///< LGPIO13
#define PAD_PIN_LGPIO14	(PAD_PIN_LGPIO_BASE + 14)	///< LGPIO14
#define PAD_PIN_LGPIO15	(PAD_PIN_LGPIO_BASE + 15)	///< LGPIO15

#define PAD_PIN_LGPIO16	(PAD_PIN_LGPIO_BASE + 16)	///< LGPIO16
#define PAD_PIN_LGPIO17	(PAD_PIN_LGPIO_BASE + 17)	///< LGPIO17
#define PAD_PIN_LGPIO18	(PAD_PIN_LGPIO_BASE + 18)	///< LGPIO18
#define PAD_PIN_LGPIO19	(PAD_PIN_LGPIO_BASE + 19)	///< LGPIO19
#define PAD_PIN_LGPIO20	(PAD_PIN_LGPIO_BASE + 20)	///< LGPIO20
#define PAD_PIN_LGPIO21	(PAD_PIN_LGPIO_BASE + 21)	///< LGPIO21
#define PAD_PIN_LGPIO22	(PAD_PIN_LGPIO_BASE + 22)	///< LGPIO22
#define PAD_PIN_LGPIO23	(PAD_PIN_LGPIO_BASE + 23)	///< LGPIO23
#define PAD_PIN_LGPIO24	(PAD_PIN_LGPIO_BASE + 24)	///< LGPIO24
#define PAD_PIN_LGPIO25	(PAD_PIN_LGPIO_BASE + 25)	///< LGPIO25
#define PAD_PIN_LGPIO26	(PAD_PIN_LGPIO_BASE + 26)	///< LGPIO26
#define PAD_PIN_LGPIO27	(PAD_PIN_LGPIO_BASE + 27)	///< LGPIO27
#define PAD_PIN_LGPIO28	(PAD_PIN_LGPIO_BASE + 28)	///< LGPIO28
#define PAD_PIN_LGPIO29	(PAD_PIN_LGPIO_BASE + 29)	///< LGPIO29
#define PAD_PIN_LGPIO30	(PAD_PIN_LGPIO_BASE + 30)	///< LGPIO30
#define PAD_PIN_LGPIO31	(PAD_PIN_LGPIO_BASE + 31)	///< LGPIO31
#define PAD_PIN_LGPIO32	(PAD_PIN_LGPIO_BASE + 32)	///< LGPIO32
//LGPIOx group end

//DGPIO group begin
#define PAD_PIN_DGPIO_BASE 300
#define PAD_PIN_DGPIO0	(PAD_PIN_DGPIO_BASE + 0)	///< DGPIO0
#define PAD_PIN_DGPIO1	(PAD_PIN_DGPIO_BASE + 1)	///< DGPIO1
#define PAD_PIN_DGPIO2	(PAD_PIN_DGPIO_BASE + 2)	///< DGPIO2
#define PAD_PIN_DGPIO3	(PAD_PIN_DGPIO_BASE + 3)	///< DGPIO3
#define PAD_PIN_DGPIO4	(PAD_PIN_DGPIO_BASE + 4)	///< DGPIO4
#define PAD_PIN_DGPIO5	(PAD_PIN_DGPIO_BASE + 5)	///< DGPIO5
#define PAD_PIN_DGPIO6	(PAD_PIN_DGPIO_BASE + 6)	///< DGPIO6
#define PAD_PIN_DGPIO7	(PAD_PIN_DGPIO_BASE + 7)	///< DGPIO7
#define PAD_PIN_DGPIO8	(PAD_PIN_DGPIO_BASE + 8)	///< DGPIO8
#define PAD_PIN_DGPIO9	(PAD_PIN_DGPIO_BASE + 9)	///< DGPIO9
#define PAD_PIN_DGPIO10	(PAD_PIN_DGPIO_BASE + 10)	///< DGPIO10
#define PAD_PIN_DGPIO11	(PAD_PIN_DGPIO_BASE + 11)	///< DGPIO11
#define PAD_PIN_DGPIO12	(PAD_PIN_DGPIO_BASE + 12)	///< DGPIO12

const struct pad_pullupdown_pin pad_pullupdown_table[] = {
	// PUPD0 //0x00
	{PAD_PIN_CGPIO0, 0, 0}, {PAD_PIN_CGPIO1, 0, 2}, {PAD_PIN_CGPIO2, 0, 4}, {PAD_PIN_CGPIO3, 0, 6},
	{PAD_PIN_CGPIO4, 0, 8}, {PAD_PIN_CGPIO5, 0, 10}, {PAD_PIN_CGPIO6, 0, 12}, {PAD_PIN_CGPIO7, 0, 14},
	{PAD_PIN_CGPIO8, 0, 16}, {PAD_PIN_CGPIO9, 0, 18}, {PAD_PIN_CGPIO10, 0, 20}, {PAD_PIN_CGPIO11, 0, 22},
	{PAD_PIN_CGPIO12, 0, 24}, {PAD_PIN_CGPIO13, 0, 26}, {PAD_PIN_CGPIO14, 0, 28}, {PAD_PIN_CGPIO15, 0, 30},
	// PUPD1 //0x04
	{PAD_PIN_CGPIO16, 1, 0}, {PAD_PIN_CGPIO17, 1, 2}, {PAD_PIN_CGPIO18, 1, 4}, {PAD_PIN_CGPIO19, 1, 6},
	{PAD_PIN_CGPIO20, 1, 8}, {PAD_PIN_CGPIO21, 1, 10}, {PAD_PIN_CGPIO22, 1, 12}, {PAD_PIN_CGPIO23, 1, 14},
	{PAD_PIN_CGPIO24, 1, 16}, {PAD_PIN_CGPIO25, 1, 18}, {PAD_PIN_CGPIO26, 1, 20}, {PAD_PIN_CGPIO27, 1, 22},
	{PAD_PIN_CGPIO28, 1, 24}, {PAD_PIN_CGPIO29, 1, 26}, {PAD_PIN_CGPIO30, 1, 28}, {PAD_PIN_CGPIO31, 1, 30},
	// PUPD2 //0x08
	{PAD_PIN_CGPIO32, 2, 0}, {PAD_PIN_CGPIO33, 2, 2},
	// PUPD3 //0x0C
	{PAD_PIN_SGPIO0, 3, 0}, {PAD_PIN_SGPIO1, 3, 2}, {PAD_PIN_SGPIO2, 3, 4}, {PAD_PIN_SGPIO3, 3, 6},
	{PAD_PIN_SGPIO4, 3, 8}, {PAD_PIN_SGPIO5, 3, 10}, {PAD_PIN_SGPIO6, 3, 12}, {PAD_PIN_SGPIO7, 3, 14},
	{PAD_PIN_SGPIO8, 3, 16}, {PAD_PIN_SGPIO9, 3, 18}, {PAD_PIN_SGPIO10, 3, 20}, {PAD_PIN_SGPIO11, 3, 22},
	// PUPD4 //0x10
	{PAD_PIN_PGPIO0, 4, 0}, {PAD_PIN_PGPIO1, 4, 2}, {PAD_PIN_PGPIO2, 4, 4}, {PAD_PIN_PGPIO3, 4, 6},
	{PAD_PIN_PGPIO4, 4, 8}, {PAD_PIN_PGPIO5, 4, 10}, {PAD_PIN_PGPIO6, 4, 12}, {PAD_PIN_PGPIO7, 4, 14},
	{PAD_PIN_PGPIO8, 4, 16}, {PAD_PIN_PGPIO9, 4, 18}, {PAD_PIN_PGPIO10, 4, 20}, {PAD_PIN_PGPIO11, 4, 22},
	{PAD_PIN_PGPIO12, 4, 24}, {PAD_PIN_PGPIO13, 4, 26}, {PAD_PIN_PGPIO14, 4, 28}, {PAD_PIN_PGPIO15, 4, 30},
	// PUPD5 //0x14
	{PAD_PIN_PGPIO16, 5, 0}, {PAD_PIN_PGPIO17, 5, 2}, {PAD_PIN_PGPIO18, 5, 4}, {PAD_PIN_PGPIO19, 5, 6},
	{PAD_PIN_PGPIO20, 5, 8}, {PAD_PIN_PGPIO21, 5, 10}, {PAD_PIN_PGPIO22, 5, 12}, {PAD_PIN_PGPIO23, 5, 14},
	{PAD_PIN_PGPIO24, 5, 16}, {PAD_PIN_PGPIO25, 5, 18}, {PAD_PIN_DGPIO8, 5, 20}, {PAD_PIN_PGPIO27, 5, 22},
	{PAD_PIN_PGPIO28, 5, 24}, {PAD_PIN_PGPIO29, 5, 26}, {PAD_PIN_PGPIO30, 5, 28}, {PAD_PIN_PGPIO31, 5, 30},
	// PUPD6 //0x18
	{PAD_PIN_PGPIO32, 6, 0}, {PAD_PIN_PGPIO33, 6, 2}, {PAD_PIN_PGPIO34, 6, 4}, {PAD_PIN_PGPIO35, 6, 6},
	{PAD_PIN_PGPIO36, 6, 8}, {PAD_PIN_PGPIO37, 6, 10}, {PAD_PIN_PGPIO38, 6, 12}, {PAD_PIN_PGPIO39, 6, 14},
	{PAD_PIN_PGPIO40, 6, 16}, {PAD_PIN_PGPIO41, 6, 18}, {PAD_PIN_PGPIO42, 6, 20}, {PAD_PIN_PGPIO43, 6, 22},
	{PAD_PIN_PGPIO44, 6, 24}, {PAD_PIN_PGPIO45, 6, 26}, {PAD_PIN_PGPIO46, 6, 28}, {PAD_PIN_PGPIO47, 6, 30},
	// PUPD7 //0x1C
	{PAD_PIN_LGPIO0, 7, 0}, {PAD_PIN_LGPIO1, 7, 2}, {PAD_PIN_LGPIO2, 7, 4}, {PAD_PIN_LGPIO3, 7, 6},
	{PAD_PIN_LGPIO4, 7, 8}, {PAD_PIN_LGPIO5, 7, 10}, {PAD_PIN_LGPIO6, 7, 12}, {PAD_PIN_LGPIO7, 7, 14},
	{PAD_PIN_LGPIO8, 7, 16}, {PAD_PIN_LGPIO9, 7, 18}, {PAD_PIN_LGPIO10, 7, 20}, {PAD_PIN_LGPIO11, 7, 22},
	{PAD_PIN_LGPIO12, 7, 24}, {PAD_PIN_LGPIO13, 7, 26}, {PAD_PIN_LGPIO14, 7, 28}, {PAD_PIN_LGPIO15, 7, 30},
	// PUPD8 //0x20
	{PAD_PIN_LGPIO16, 8, 0}, {PAD_PIN_LGPIO17, 8, 2}, {PAD_PIN_LGPIO18, 8, 4}, {PAD_PIN_LGPIO19, 8, 6},
	{PAD_PIN_LGPIO20, 8, 8}, {PAD_PIN_LGPIO21, 8, 10}, {PAD_PIN_LGPIO22, 8, 12}, {PAD_PIN_LGPIO23, 8, 14},
	{PAD_PIN_LGPIO24, 8, 16}, {PAD_PIN_LGPIO25, 8, 18}, {PAD_PIN_LGPIO26, 8, 20}, {PAD_PIN_LGPIO27, 8, 22},
	{PAD_PIN_LGPIO28, 8, 24}, {PAD_PIN_LGPIO29, 8, 26}, {PAD_PIN_LGPIO30, 8, 28}, {PAD_PIN_LGPIO31, 8, 30},
	// PUPD9 //0x24
	{PAD_PIN_LGPIO32, 9, 0},
	// PUPD10 //0x28
	{PAD_PIN_DGPIO0, 10, 0}, {PAD_PIN_DGPIO1, 10, 2}, {PAD_PIN_DGPIO2, 10, 4}, {PAD_PIN_DGPIO3, 10, 6},
	{PAD_PIN_DGPIO4, 10, 8}, {PAD_PIN_DGPIO5, 10, 10}, {PAD_PIN_DGPIO6, 10, 12}, {PAD_PIN_DGPIO7, 10, 14},
	{PAD_PIN_DGPIO8, 10, 16}, {PAD_PIN_DGPIO9, 10, 18}, {PAD_PIN_DGPIO10, 10, 20}, {PAD_PIN_DGPIO11, 10, 22},
	{PAD_PIN_DGPIO12, 10, 24},
};

#endif