//This source code is generated by UI Designer Studio.

#ifndef FLOWCOMMONRES_H
#define FLOWCOMMONRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(FlowCommon)
SHOW_MAP_END

DECLARE_EVENT(FlowCommon)
DECLARE_CTRL_LIST(FlowCommon)
CREATE_CTRL(FlowCommon, FlowCommon, CTRL_BASE, NULL, 0, 0, 0, 319, 239)
#endif
