//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFORMAT_H
#define UIMENUWNDSETUPFORMAT_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFormatCtrl;//Panel type

extern VControl UIMenuWndSetupFormat_List_TextCtrl;//List type

typedef enum {
	UIMenuWndSetupFormat_List_Text_STRID_INT_FLASH,
	UIMenuWndSetupFormat_List_Text_STRID_EXT_CARD,
	UIMenuWndSetupFormat_List_Text_MAX
} UIMenuWndSetupFormat_List_Text_Setting;

#endif
