//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupVersionRes.c"
#include "UIMenuWndSetupVersion.h"
//#include "UIMenuWndSetupLoaderVersion.h"
#include "MenuCommonItem.h"
#include "UIFlow.h"

#define LD_VERSION_DISPLAY      ENABLE//DISABLE

//---------------------UIMenuWndSetupVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupVersion)
CTRL_LIST_ITEM(UIMenuSetupVersionText)
CTRL_LIST_ITEM(UIMenuSetupVersionText2)
CTRL_LIST_END

//----------------------UIMenuWndSetupVersionCtrl Event---------------------------
INT32 UIMenuWndSetupVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndSetupVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndSetupVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIMenuWndSetupVersion_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIMenuWndSetupVersion_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIMenuWndSetupVersion_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndSetupVersion_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndSetupVersion_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIMenuWndSetupVersion_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UxStatic_SetData(&UIMenuSetupVersionText2Ctrl, STATIC_VALUE, Txt_Pointer(Prj_GetVersionString()));
	UxStatic_SetData(&UIMenuSetupVersionTextCtrl, STATIC_VALUE, Txt_Pointer(Prj_GetVersionString()));
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (LD_VERSION_DISPLAY == ENABLE)
	//Ux_OpenWindow(&UIMenuWndSetupLoaderVersionCtrl,0);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&UIMenuWndSetupVersionCtrl, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupVersion_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_LIVEVIEW_MODE, 0);
	return NVTEVT_CONSUME;
#else
	// the same behavior as ENTER key!
	return UIMenuWndSetupVersion_OnKeyEnter(pCtrl, paramNum, paramArray);
#endif
}
//----------------------UIMenuSetupVersionTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText)
EVENT_END

//----------------------UIMenuSetupVersionText2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuSetupVersionText2)
EVENT_END
