//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPFORMATCONFIRM_H
#define UIMENUWNDSETUPFORMATCONFIRM_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupFormatConfirmCtrl;//Panel type

extern VControl UIMenuWndSetupFormatConfirm_List_TextCtrl;//List type

typedef enum {
	UIMenuWndSetupFormatConfirm_List_Text_STRID_CANCEL,
	UIMenuWndSetupFormatConfirm_List_Text_STRID_OK,
	UIMenuWndSetupFormatConfirm_List_Text_MAX
} UIMenuWndSetupFormatConfirm_List_Text_Setting;

extern VControl UIMenuWndSetupFormatConfirm_Static_TextCtrl;//Static type

#endif
