//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPDEFAULTSETTING_H
#define UIMENUWNDSETUPDEFAULTSETTING_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupDefaultSettingCtrl;//Panel type

extern VControl UIMenuWndSetupDefaultSetting_List_TextCtrl;//List type

typedef enum {
	UIMenuWndSetupDefaultSetting_List_Text_STRID_CANCEL,
	UIMenuWndSetupDefaultSetting_List_Text_STRID_OK,
	UIMenuWndSetupDefaultSetting_List_Text_MAX
} UIMenuWndSetupDefaultSetting_List_Text_Setting;

extern VControl UIMenuWndSetupDefaultSetting_Static_TextCtrl;//Static type

#endif
