//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPVERSION_H
#define UIMENUWNDSETUPVERSION_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupVersionCtrl;//Panel type

extern VControl UIMenuSetupVersionTextCtrl;//Static type

extern VControl UIMenuSetupVersionText2Ctrl;//Static type

#endif
