//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPDATETIME_H
#define UIMENUWNDSETUPDATETIME_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupDateTimeCtrl;//Panel type

extern VControl UIMenuWndSetupDateTime_TabCtrl;//Tab type

typedef enum {
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_Y,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_Y2,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_Y3,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_Y4,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_M,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_M2,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_D,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_D2,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_HR,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_HR2,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_MIN,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_YMD_MIN2,
	UIMenuWndSetupDateTime_Tab_UIMenuWndSetupDateTime_Tab_YMD_VALUE,
	UIMenuWndSetupDateTime_Tab_MAX
} UIMenuWndSetupDateTime_Tab_Setting;

extern VControl UIMenuWndSetupDateTime_YMD_YCtrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_Y2Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_Y3Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_Y4Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_MCtrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_M2Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_DCtrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_D2Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_HRCtrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_HR2Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_MINCtrl;//Button type

extern VControl UIMenuWndSetupDateTime_YMD_MIN2Ctrl;//Button type

extern VControl UIMenuWndSetupDateTime_Tab_YMD_VALUECtrl;//Tab type

typedef enum {
	UIMenuWndSetupDateTime_Tab_YMD_VALUE_UIMenuWndSetupDateTime_YMD_VALUE_Other0,
	UIMenuWndSetupDateTime_Tab_YMD_VALUE_UIMenuWndSetupDateTime_YMD_VALUE_Other1,
	UIMenuWndSetupDateTime_Tab_YMD_VALUE_UIMenuWndSetupDateTime_YMD_VALUE_Other2,
	UIMenuWndSetupDateTime_Tab_YMD_VALUE_MAX
} UIMenuWndSetupDateTime_Tab_YMD_VALUE_Setting;

extern VControl UIMenuWndSetupDateTime_YMD_VALUE_Other0Ctrl;//Static type

extern VControl UIMenuWndSetupDateTime_YMD_VALUE_Other1Ctrl;//Static type

extern VControl UIMenuWndSetupDateTime_YMD_VALUE_Other2Ctrl;//Static type

//---------------------UIMenuWndSetupDateTimeCtrl User Export---------------------------
#endif
