#include "SysKer.h"
#include "AppDisp_MoviePlayView.h"

#define PRI_APPDISP_MOVIEPLAYVIEW			5
#define STKSIZE_APPDISP_MOVIEPLAYVIEW		4096

UINT32 APPDISP_MOVIEPLAYVIEW_FLG_ID = 0;
UINT32 APPDISP_MOVIEPLAYVIEW_TSK_ID = 0;

void AppDisp_MoviePlayView_InstallID(void)
{
	OS_CONFIG_FLAG(APPDISP_MOVIEPLAYVIEW_FLG_ID);
	OS_CONFIG_TASK(APPDISP_MOVIEPLAYVIEW_TSK_ID,   PRI_APPDISP_MOVIEPLAYVIEW,  STKSIZE_APPDISP_MOVIEPLAYVIEW,  AppDisp_MoviePlayView_Tsk);
}
