//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlaySlideShowCBRes.c"
#include "UIMenuWndPlaySlideShowCB.h"
#include "UIFlowWndPlay.h"
#include "UIFlowPlayFuncs.h"
#include "UIMenuWndPlaySlideShow.h"
#include "MenuCommonItem.h"
#include "PlaybackTsk.h"
#include "UIFlow.h"
#include "DCF.h"
#include "UIPlayComm.h"
#define SLIDESHOW_JPEG_ONLY     0

typedef enum {
	Playback_FileFmt_JPG,
	Playback_FileFmt_ALL,
} Playback_FileFmt;

//---------------------UIMenuWndPlaySlideShowCBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlaySlideShowCB)
CTRL_LIST_END

//----------------------UIMenuWndPlaySlideShowCBCtrl Event---------------------------
INT32 UIMenuWndPlaySlideShowCB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShowCB_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlaySlideShowCB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndPlaySlideShowCB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndPlaySlideShowCB_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIMenuWndPlaySlideShowCB_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU, UIMenuWndPlaySlideShowCB_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE, UIMenuWndPlaySlideShowCB_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIMenuWndPlaySlideShowCB_OnKeyShutter2)
EVENT_ITEM(NVTEVT_TIMER, UIMenuWndPlaySlideShowCB_OnTimer)
EVENT_END

static void FlowPB_SetKeyMask(UINT32 press, UINT32 release)
{
	Input_SetKeyMask(KEY_PRESS, press);
	Input_SetKeyMask(KEY_RELEASE, release);
}


static UINT32 gSlideTimerID = NULL_TIMER;

#if SLIDESHOW_JPEG_ONLY
static void UIMEnuWndPlaySlideShowCB_SetFileFmt(Playback_FileFmt PB_FileFmt)
{
	PLAY_OBJ PlayObj = {0};
	UINT PBFileFmt;

	// get playback object
	PB_GetParam(PBPRMID_PLAYBACK_OBJ, (UINT32 *)&PlayObj);

	FileSys_WaitFinish();
	//step1. close current active file
	FileSys_CloseFile((FST_FILE)0xFFFFFFFF);
	//step2. rescan file format
	switch (PB_FileFmt) {
	case Playback_FileFmt_JPG:
	default:
		PBFileFmt = DCF_FILE_TYPE_JPG;
		PlayObj.uiPlayFileFmt = PBFMT_JPG;
		break;

	case Playback_FileFmt_ALL:
		PBFileFmt = DCF_FILE_TYPE_JPG | DCF_FILE_TYPE_AVI | DCF_FILE_TYPE_MOV | DCF_FILE_TYPE_MP4;
		PlayObj.uiPlayFileFmt = PBFMT_JPG | PBFMT_AVI | PBFMT_MOVMJPG | PBFMT_MP4;

#if (_WAVSTUDIO_MODE_ == ENABLE)
		PBFileFmt |= DCF_FILE_TYPE_WAV;
		PlayObj.uiPlayFileFmt |= PBFMT_WAV;
#endif
		break;
	}
	//DCF_SetParm(DCF_PRMID_SET_VALID_FILE_FMT,PBFileFmt);
	//DCF_ScanObj();

	// slide show only for jpg file format
	PB_SetParam(PBPRMID_PLAYBACK_OBJ, (UINT32)&PlayObj);
}
#endif

INT32 UIMenuWndPlaySlideShowCB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//#NT#2009/08/03#Chris Chung -begin
	UINT32 uiSlideInterval;
	UINT32 uiFileNum = 0;

	if (paramNum == 1) {
		uiSlideInterval = paramArray[0];
	} else {
		uiSlideInterval = 2000; // default slide show time interval is 2sec
	}

#if SLIDESHOW_JPEG_ONLY
	UIMEnuWndPlaySlideShowCB_SetFileFmt(Playback_FileFmt_JPG);
#endif
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
	if (uiFileNum > 0) {
#if SLIDESHOW_JPEG_ONLY
		// play next if current file format is video
		UINT32 uiFileFmt;
		PB_GetParam(PBPRMID_CURR_FILEFMT, &uiFileFmt);
		while (uiFileFmt & PBFMT_AVI || uiFileFmt & PBFMT_MOVMJPG) {
			UIPlay_PlaySingle(PB_SINGLE_NEXT);
		}
		PB_GetParam(PBPRMID_CURR_FILEFMT, &uiFileFmt);
		if (uiFileFmt & PBFMT_JPG)
#endif
		{
			gSlideTimerID = GxTimer_StartTimer(uiSlideInterval, NVTEVT_DISPTIMER, CONTINUE);
		}
	} else {
		Ux_PostEvent(NVTEVT_KEY_ENTER, 1, NVTEVT_KEY_PRESS);
	}

	FlowPB_SetKeyMask(FLGKEY_KEY_MASK_DEFAULT, FLGKEY_KEY_MASK_NULL);

	//#NT#2009/08/03#Chris Chung -end
	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShowCB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	// Close timer
	GxTimer_StopTimer(&gSlideTimerID);

	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShowCB_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if SLIDESHOW_JPEG_ONLY
	// restore for all legal playback file formats
	UIMEnuWndPlaySlideShowCB_SetFileFmt(Playback_FileFmt_ALL);
#endif

	Ux_FlushEventByRange(NVTEVT_TIMER, NVTEVT_TIMER);
	GxTimer_StopTimer(&gSlideTimerID);

	Ux_CloseWindow(&UIMenuWndPlaySlideShowCBCtrl, 0);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShowCB_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if SLIDESHOW_JPEG_ONLY
	UIMEnuWndPlaySlideShowCB_SetFileFmt(Playback_FileFmt_ALL);
#endif

	Ux_CloseWindow(&MenuCommonItemCtrl, 0); // close whole tab menu
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShowCB_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_EXE_CHANGEDSCMODE, 1, DSCMODE_CHGTO_NEXT);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShowCB_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 0
	Ux_SendEvent(&UISetupObjCtrl, NVTEVT_FORCETO_LIVEVIEW_MODE, 0);
	return NVTEVT_CONSUME;
#else
	// the same behavior as ENTER key!
	return UIMenuWndPlaySlideShowCB_OnKeyMenu(pCtrl, paramNum, paramArray);
#endif
}
INT32 UIMenuWndPlaySlideShowCB_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	NVTEVT event;

	event = paramArray[0];
	if (event == NVTEVT_DISPTIMER) {
		FlowPB_SetKeyMask(FLGKEY_KEY_MASK_DEFAULT & ~(FLGKEY_RIGHT | FLGKEY_LEFT), FLGKEY_KEY_MASK_NULL);
		Ux_FlushEventByRange(NVTEVT_TIMER, NVTEVT_TIMER);
		UIPlay_PlaySingle(PB_SINGLE_NEXT);
		FlowPB_SetKeyMask(FLGKEY_KEY_MASK_DEFAULT, FLGKEY_KEY_MASK_NULL);
	}

	return NVTEVT_CONSUME;
}
