//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYSLIDESHOW_H
#define UIMENUWNDPLAYSLIDESHOW_H

#include "UIFramework.h"

extern VControl UIMenuWndPlaySlideShowCtrl;//Panel type

extern VControl UIMenuWndPlaySlideShow_PanelCtrl;//Panel type

extern VControl UIMenuWndPlaySlideShow_MenuCtrl;//Menu type

typedef enum {
	UIMenuWndPlaySlideShow_Menu_STRID_2SEC,
	UIMenuWndPlaySlideShow_Menu_STRID_5SEC,
	UIMenuWndPlaySlideShow_Menu_STRID_8SEC,
	UIMenuWndPlaySlideShow_Menu_MAX
} UIMenuWndPlaySlideShow_Menu_Setting;

#endif
