//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPLAYDEL_H
#define UIMENUWNDPLAYDEL_H

#include "UIFramework.h"

extern VControl UIMenuWndPlayDelCtrl;//Panel type

extern VControl UIMenuWndPlayDel_PanelCtrl;//Panel type

extern VControl UIMenuWndPlayDel_MenuCtrl;//Menu type

typedef enum {
	UIMenuWndPlayDel_Menu_STRID_DELETECURRENT,
	UIMenuWndPlayDel_Menu_STRID_DELETEALL,
	UIMenuWndPlayDel_Menu_MAX
} UIMenuWndPlayDel_Menu_Setting;

#endif
