INCLUDES = -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I../mediaServer/include
#PREFIX = /usr/local
PREFIX = ../../../release/nvtlive555
LIBDIR = $(PREFIX)/lib
##### Change the following for your environment:
