//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDUSB_H
#define UIFLOWWNDUSB_H

#include "UIFramework.h"

extern VControl UIFlowWndUSBCtrl;//Panel type

extern VControl UIFlowWndMSDC_StaticTxt_MassStorageCtrl;//Static type

#endif
