//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDUSBAPI_H
#define UIFLOWWNDUSBAPI_H

enum {
	UIFlowWndUSB_MSDC_MODE = 0x00,
	UIFlowWndUSB_PCC_MODE,
	UIFlowWndUSB_LOADING_MODE,
};

#endif
