//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDWAITMOMENTRES_H
#define UIFLOWWNDWAITMOMENTRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin1, 0, 0, 319, 239)

SHOW_ITEM_RECT(CMD_Rectangle, Rect5, 0, 0, 219, 139, 16, 0, 0, 14, 0, 0, 0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Rect5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin3, 0, 0, 219, 139)

SHOW_ITEM_TEXT(CMD_Text | CMD_ITEM, Text7, 0, 58, 219, 139, STRID_NULL, 0, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Text7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal2, 50, 50, 269, 189)

CREATE_STATE_ITEM_DATA(STRID_PLEASE_WAIT8, STRID_PLEASE_WAIT, ICONID_NULL, NULL)
SHOW_MAP_BEGIN(UIFlowWndWaitMoment_StatusTXT_Msg)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndWaitMoment_StatusTXT_Msg)
STATE_LIST_BEGIN(UIFlowWndWaitMoment_StatusTXT_Msg)
STATE_LIST_ITEM(STRID_PLEASE_WAIT8)
STATE_LIST_END

CREATE_STATE_DATA(UIFlowWndWaitMoment_StatusTXT_Msg, 0)
CREATE_STATE_CTRL(UIFlowWndWaitMoment_StatusTXT_Msg, 0, 50, 50, 269, 189)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndWaitMoment)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndWaitMoment)
DECLARE_CTRL_LIST(UIFlowWndWaitMoment)
CREATE_CTRL(UIFlowWndWaitMoment, UIFlowWndWaitMoment, CTRL_WND, NULL, 0, 0, 0, 319, 239)
#endif
