#
# Makefile for the Synopsys network device drivers.
#
obj-m += ntkimethmac.o
ntkimethmac-objs := DWC_ETH_QOS.o DWC_ETH_QOS_mdio.o \
			DWC_ETH_QOS_dev.o DWC_ETH_QOS_desc.o \
			DWC_ETH_QOS_drv.o DWC_ETH_QOS_ethtool.o