//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIWAIT_H
#define UIMENUWNDWIFIWAIT_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiWaitCtrl;//Panel type

extern VControl UIMenuWndWiFiWait_StatusGraphCtrl;//StatusGraph type

typedef enum {
	UIMenuWndWiFiWait_StatusGraph_State_WiFi_1,
	UIMenuWndWiFiWait_StatusGraph_State_WiFi_2,
	UIMenuWndWiFiWait_StatusGraph_State_WiFi_3,
	UIMenuWndWiFiWait_StatusGraph_State_WiFi_ON,
	UIMenuWndWiFiWait_StatusGraph_State_WiFi_OFF,
	UIMenuWndWiFiWait_StatusGraph_MAX
} UIMenuWndWiFiWait_StatusGraph_Setting;

//---------------------UIMenuWndWiFiWaitCtrl User Export---------------------------
#endif
