//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIQRCODESCANRES_H
#define UIMENUWNDWIFIQRCODESCANRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,319,239,0,0,0,0,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,319,239)

SHOW_ITEM_RECT(CMD_Rectangle,Skin3Rect,0,0,223,25,0,0,14,14,0,0,0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Skin3Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin3,0,0,223,25)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text5,0,0,223,24,STRID_NULL,0,0,0,0,2,1,1,256,0,1,0,0,0,0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Text5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal2,55,209,278,234)

CREATE_STATE_ITEM_DATA(STRID_NULL_6,STRID_NULL_,ICONID_NULL,NULL) 
SHOW_MAP_BEGIN(UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan)
STATE_LIST_BEGIN(UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan)
STATE_LIST_ITEM(STRID_NULL_6)
STATE_LIST_END

CREATE_STATE_DATA(UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan,0)
CREATE_STATE_CTRL(UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan,0,55,209,278,234)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIMenuWndWiFiQRCodeScan)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIMenuWndWiFiQRCodeScan)
DECLARE_CTRL_LIST(UIMenuWndWiFiQRCodeScan)
CREATE_CTRL(UIMenuWndWiFiQRCodeScan,UIMenuWndWiFiQRCodeScan,CTRL_WND,NULL,0 ,0,0,319,239)
#endif
