//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiLivestreamRes.c"
#include "UIMenuWndWiFiLivestream.h"
#include "PrjCfg.h"
#include "UIFlow.h"
#include "NvtIpcAPI.h"
#include "Debug.h"


///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          ISF_STREAMSENDER
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"
///////////////////////////////////////////////////////////////////////////////

#define LIVESTREAM_IPC_TOKEN_PATH    "livestream"
#define LIVESTREAM_INVALID_MSGID     NVTIPC_MSG_QUEUE_NUM+1
#define LIVESTREAM_SEND_TARGET       NVTIPC_SENDTO_CORE2

typedef enum {
	LIVESTREAM_CMDID_START  =   0x00000000,
	LIVESTREAM_CMDID_STOP,
	LIVESTREAM_CMDID_ACK,
	LIVESTREAM_CMDID_MAX_ID,
	ENUM_DUMMY4WORD(LIVESTREAM_RCV_CMDID)
} LIVESTREAM_CMDID;

typedef struct {
	LIVESTREAM_CMDID CmdId;
} LIVESTREAM_MSG;

//global variables
static NVTIPC_U32 gIPC_MsgId  = LIVESTREAM_INVALID_MSGID;

//---------------------UIMenuWndWiFiLivestreamCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFILIVESTREAM_ERROR_MSG        1
#define _UIMENUWNDWIFILIVESTREAM_TRACE_MSG        0

#if (_UIMENUWNDWIFILIVESTREAM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiLivestreamErrMsg(...)            debug_msg ("^R UIMenuWndWiFiLivestream: "__VA_ARGS__)
#else
#define UIMenuWndWiFiLivestreamErrMsg(...)
#endif

#if (_UIMENUWNDWIFILIVESTREAM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiLivestreamTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiLivestream: "__VA_ARGS__)
#else
#define UIMenuWndWiFiLivestreamTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiLivestreamCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiLivestreamCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiLivestreamCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiLivestream)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_StaticICN_WiFi)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_StatusTXT_Livestream)
CTRL_LIST_ITEM(UIMenuWndWiFiLivestream_Tab_Off)
CTRL_LIST_END

//----------------------UIMenuWndWiFiLivestreamCtrl Event---------------------------
INT32 UIMenuWndWiFiLivestream_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiLivestream_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiLivestream)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiLivestream_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiLivestream_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndWiFiLivestream_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIMenuWndWiFiLivestream_OnBattery)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndWiFiLivestream_OnTimer)
EVENT_END

INT32 UIMenuWndWiFiLivestream_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UxState_SetItemData(&UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl, 0, STATE_ITEM_STRID,  Txt_Pointer(UIRes_GetUserString(STRID_LIVESTREAM)));

	Ux_SendEvent(0, NVTEVT_EXE_WIFI_LIVESTREAM, 0);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiLivestream_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiLivestream_StaticICN_WiFiCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiLivestream_StaticICN_WiFi)
EVENT_END

//----------------------UIMenuWndWiFiLivestream_StatusTXT_LivestreamCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiLivestream_StatusTXT_Livestream)
EVENT_END

//----------------------UIMenuWndWiFiLivestream_Tab_OffCtrl Event---------------------------
INT32 UIMenuWndWiFiLivestream_Tab_Off_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiLivestream_Tab_Off)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndWiFiLivestream_Tab_Off_OnKeyEnter)
EVENT_END

INT32 UIMenuWndWiFiLivestream_Tab_Off_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiKeyAct;
	NVTIPC_I32 Ret_NvtIpc;
	LIVESTREAM_MSG Msg ={0};

	uiKeyAct = paramArray[0];
	switch (uiKeyAct) {
	case NVTEVT_KEY_PRESS:
		Ret_NvtIpc = NvtIPC_MsgGet(NvtIPC_Ftok(LIVESTREAM_IPC_TOKEN_PATH));
		if (Ret_NvtIpc < 0) {
			DBG_ERR("%s: NvtIPC_MsgGet = %d\r\n", __func__, Ret_NvtIpc);
			return NVTEVT_CONSUME;
		}
		
		gIPC_MsgId = (NVTIPC_U32)Ret_NvtIpc;
		DBG_IND("[IPC]Got MsgId(%d)\r\n", gIPC_MsgId);
		
		Msg.CmdId = LIVESTREAM_CMDID_STOP;
		Ret_NvtIpc = NvtIPC_MsgSnd(gIPC_MsgId, NVTIPC_SENDTO_CORE2, (void *)&Msg, sizeof(Msg));
		if (Ret_NvtIpc < 0) {
			DBG_ERR("NvtIPC_MsgSnd = %d\r\n", __func__, Ret_NvtIpc);
			return NVTEVT_CONSUME;
		}
		
		Ret_NvtIpc = NvtIPC_MsgRcv(gIPC_MsgId, (void *)&Msg, sizeof(Msg));
		if (Ret_NvtIpc < 0) {
			DBG_ERR("NvtIPC_MsgRcv = %d\r\n", __func__, Ret_NvtIpc);
		}

		Ret_NvtIpc = NvtIPC_MsgRel(gIPC_MsgId);
		if (Ret_NvtIpc < 0) {
			DBG_ERR("NvtIPC_MsgRel = %d\r\n", Ret_NvtIpc);
		}
					
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		//should close network application,then stop wifi
		Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);			
		break;
	}

    return NVTEVT_CONSUME;
}
//----------------------Button_LivestreamOffCtrl Event---------------------------
EVENT_BEGIN(Button_LivestreamOff)
EVENT_END

