//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIMOBILELINKOK_H
#define UIMENUWNDWIFIMOBILELINKOK_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiMobileLinkOKCtrl;//Panel type

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl;//Static type

extern VControl UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl;//Button type

extern VControl UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl;//Static type
//---------------------UIMenuWndWiFiMobileLinkOKCtrl User Export---------------------------
#endif
