//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDWIFIQRCODESCAN_H
#define UIMENUWNDWIFIQRCODESCAN_H

#include "UIFramework.h"

extern VControl UIMenuWndWiFiQRCodeScanCtrl;//Panel type 

extern VControl UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScanCtrl;//Status type 

typedef enum
{
UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan_STRID_NULL_,
UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan_MAX
}UIMenuWndWiFiQRCodeScan_StatusTXT_QRCodeScan_Setting;

//---------------------UIMenuWndWiFiQRCodeScanCtrl User Export---------------------------
#endif
