//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYTHUMB_H
#define UIFLOWWNDPLAYTHUMB_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayThumbCtrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel0Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel1Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel2Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel3Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel4Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel5Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel6Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel7Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_Panel8Ctrl;//Panel type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect0Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect1Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect2Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect3Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect4Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect5Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect6Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect7Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_Protect8Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm0Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm1Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm2Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm3Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm4Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm5Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm6Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm7Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_StaticICN_FileFilm8Ctrl;//Static type

extern VControl UIFlowWndPlayThumb_ThumbIDCtrl;//Static type

#endif
