//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYTHUMBRES_H
#define UIFLOWWNDPLAYTHUMBRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle, Skin1Rect, 0, 0, 319, 239, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin1, 0, 0, 319, 239)

SHOW_ITEM_RECT(CMD_Rectangle, Rect4, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin2)
SHOW_MAP_BODY(Rect4)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin2, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel0)
SHOW_MAP_BODY(Skin2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel0)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel0)
CREATE_CTRL(UIFlowWndPlayThumb_Panel0, UIFlowWndPlayThumb_Panel0, CTRL_WND, NULL, 0, 18, 6, 101, 69)
SHOW_ITEM_RECT(CMD_Rectangle, Rect7, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin5)
SHOW_MAP_BODY(Rect7)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin5, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel1)
SHOW_MAP_BODY(Skin5)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel1)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel1)
CREATE_CTRL(UIFlowWndPlayThumb_Panel1, UIFlowWndPlayThumb_Panel1, CTRL_WND, NULL, 0, 118, 6, 201, 69)
SHOW_ITEM_RECT(CMD_Rectangle, Rect10, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin8)
SHOW_MAP_BODY(Rect10)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin8, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel2)
SHOW_MAP_BODY(Skin8)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel2)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel2)
CREATE_CTRL(UIFlowWndPlayThumb_Panel2, UIFlowWndPlayThumb_Panel2, CTRL_WND, NULL, 0, 218, 6, 301, 69)
SHOW_ITEM_RECT(CMD_Rectangle, Rect13, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin11)
SHOW_MAP_BODY(Rect13)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin11, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel3)
SHOW_MAP_BODY(Skin11)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel3)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel3)
CREATE_CTRL(UIFlowWndPlayThumb_Panel3, UIFlowWndPlayThumb_Panel3, CTRL_WND, NULL, 0, 18, 76, 101, 139)
SHOW_ITEM_RECT(CMD_Rectangle, Rect16, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin14)
SHOW_MAP_BODY(Rect16)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin14, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel4)
SHOW_MAP_BODY(Skin14)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel4)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel4)
CREATE_CTRL(UIFlowWndPlayThumb_Panel4, UIFlowWndPlayThumb_Panel4, CTRL_WND, NULL, 0, 118, 76, 201, 139)
SHOW_ITEM_RECT(CMD_Rectangle, Rect19, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin17)
SHOW_MAP_BODY(Rect19)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin17, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel5)
SHOW_MAP_BODY(Skin17)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel5)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel5)
CREATE_CTRL(UIFlowWndPlayThumb_Panel5, UIFlowWndPlayThumb_Panel5, CTRL_WND, NULL, 0, 218, 76, 301, 139)
SHOW_ITEM_RECT(CMD_Rectangle, Rect22, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin20)
SHOW_MAP_BODY(Rect22)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin20, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel6)
SHOW_MAP_BODY(Skin20)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel6)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel6)
CREATE_CTRL(UIFlowWndPlayThumb_Panel6, UIFlowWndPlayThumb_Panel6, CTRL_WND, NULL, 0, 18, 146, 101, 209)
SHOW_ITEM_RECT(CMD_Rectangle, Rect25, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin23)
SHOW_MAP_BODY(Rect25)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin23, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel7)
SHOW_MAP_BODY(Skin23)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel7)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel7)
CREATE_CTRL(UIFlowWndPlayThumb_Panel7, UIFlowWndPlayThumb_Panel7, CTRL_WND, NULL, 0, 119, 146, 202, 209)
SHOW_ITEM_RECT(CMD_Rectangle, Rect28, 0, 0, 83, 63, 272, 0, 2, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin26)
SHOW_MAP_BODY(Rect28)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin26, 0, 0, 83, 63)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_Panel8)
SHOW_MAP_BODY(Skin26)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_Panel8)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb_Panel8)
CREATE_CTRL(UIFlowWndPlayThumb_Panel8, UIFlowWndPlayThumb_Panel8, CTRL_WND, NULL, 0, 218, 146, 301, 209)
SHOW_ITEM_RECT(CMD_Rectangle, Skin30Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin30)
SHOW_MAP_BODY(Skin30Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin30, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon31, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal29)
SHOW_MAP_BODY(Skin30)
SHOW_MAP_BODY(Icon31)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal29, 44, 8, 71, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect0)
SHOW_MAP_BODY(Normal29)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect0)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect0, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect0, 0, 44, 8, 71, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin34Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin34)
SHOW_MAP_BODY(Skin34Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin34, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon35, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal33)
SHOW_MAP_BODY(Skin34)
SHOW_MAP_BODY(Icon35)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal33, 145, 8, 172, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect1)
SHOW_MAP_BODY(Normal33)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect1)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect1, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect1, 0, 145, 8, 172, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin38Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin38)
SHOW_MAP_BODY(Skin38Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin38, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon39, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal37)
SHOW_MAP_BODY(Skin38)
SHOW_MAP_BODY(Icon39)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal37, 244, 8, 271, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect2)
SHOW_MAP_BODY(Normal37)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect2)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect2, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect2, 0, 244, 8, 271, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin42Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin42)
SHOW_MAP_BODY(Skin42Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin42, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon43, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal41)
SHOW_MAP_BODY(Skin42)
SHOW_MAP_BODY(Icon43)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal41, 44, 78, 71, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect3)
SHOW_MAP_BODY(Normal41)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect3)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect3, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect3, 0, 44, 78, 71, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin46Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin46)
SHOW_MAP_BODY(Skin46Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin46, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon47, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal45)
SHOW_MAP_BODY(Skin46)
SHOW_MAP_BODY(Icon47)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal45, 145, 78, 172, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect4)
SHOW_MAP_BODY(Normal45)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect4)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect4, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect4, 0, 145, 78, 172, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin50Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin50)
SHOW_MAP_BODY(Skin50Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin50, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon51, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal49)
SHOW_MAP_BODY(Skin50)
SHOW_MAP_BODY(Icon51)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal49, 244, 78, 271, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect5)
SHOW_MAP_BODY(Normal49)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect5)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect5, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect5, 0, 244, 78, 271, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin54Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin54)
SHOW_MAP_BODY(Skin54Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin54, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon55, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal53)
SHOW_MAP_BODY(Skin54)
SHOW_MAP_BODY(Icon55)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal53, 44, 148, 71, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect6)
SHOW_MAP_BODY(Normal53)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect6)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect6, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect6, 0, 44, 148, 71, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin58Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin58)
SHOW_MAP_BODY(Skin58Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin58, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon59, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal57)
SHOW_MAP_BODY(Skin58)
SHOW_MAP_BODY(Icon59)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal57, 145, 148, 172, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect7)
SHOW_MAP_BODY(Normal57)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect7)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect7, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect7, 0, 145, 148, 172, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin62Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin62)
SHOW_MAP_BODY(Skin62Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin62, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon63, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal61)
SHOW_MAP_BODY(Skin62)
SHOW_MAP_BODY(Icon63)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal61, 244, 148, 271, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_Protect8)
SHOW_MAP_BODY(Normal61)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_Protect8)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_Protect8, ICON_LOCK)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_Protect8, 0, 244, 148, 271, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin66Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin66)
SHOW_MAP_BODY(Skin66Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin66, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon67, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal65)
SHOW_MAP_BODY(Skin66)
SHOW_MAP_BODY(Icon67)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal65, 71, 8, 98, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm0)
SHOW_MAP_BODY(Normal65)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm0)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm0, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm0, 0, 71, 8, 98, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin70Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin70)
SHOW_MAP_BODY(Skin70Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin70, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon71, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal69)
SHOW_MAP_BODY(Skin70)
SHOW_MAP_BODY(Icon71)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal69, 172, 8, 199, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm1)
SHOW_MAP_BODY(Normal69)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm1)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm1, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm1, 0, 172, 8, 199, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin74Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin74)
SHOW_MAP_BODY(Skin74Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin74, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon75, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal73)
SHOW_MAP_BODY(Skin74)
SHOW_MAP_BODY(Icon75)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal73, 272, 8, 299, 35)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm2)
SHOW_MAP_BODY(Normal73)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm2)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm2, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm2, 0, 272, 8, 299, 35)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin78Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin78)
SHOW_MAP_BODY(Skin78Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin78, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon79, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal77)
SHOW_MAP_BODY(Skin78)
SHOW_MAP_BODY(Icon79)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal77, 71, 78, 98, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm3)
SHOW_MAP_BODY(Normal77)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm3)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm3, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm3, 0, 71, 78, 98, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin82Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin82)
SHOW_MAP_BODY(Skin82Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin82, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon83, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal81)
SHOW_MAP_BODY(Skin82)
SHOW_MAP_BODY(Icon83)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal81, 172, 78, 199, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm4)
SHOW_MAP_BODY(Normal81)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm4)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm4, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm4, 0, 172, 78, 199, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin86Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin86)
SHOW_MAP_BODY(Skin86Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin86, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon87, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal85)
SHOW_MAP_BODY(Skin86)
SHOW_MAP_BODY(Icon87)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal85, 272, 78, 299, 105)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm5)
SHOW_MAP_BODY(Normal85)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm5)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm5, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm5, 0, 272, 78, 299, 105)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin90Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin90)
SHOW_MAP_BODY(Skin90Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin90, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon91, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal89)
SHOW_MAP_BODY(Skin90)
SHOW_MAP_BODY(Icon91)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal89, 71, 148, 98, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm6)
SHOW_MAP_BODY(Normal89)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm6)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm6, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm6, 0, 71, 148, 98, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin94Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin94)
SHOW_MAP_BODY(Skin94Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin94, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon95, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal93)
SHOW_MAP_BODY(Skin94)
SHOW_MAP_BODY(Icon95)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal93, 172, 148, 199, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm7)
SHOW_MAP_BODY(Normal93)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm7)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm7, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm7, 0, 172, 148, 199, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin98Rect, 0, 0, 27, 27, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin98)
SHOW_MAP_BODY(Skin98Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin98, 0, 0, 27, 27)

SHOW_ITEM_IMAGE(CMD_Image | CMD_ITEM, Icon99, 0, 0, 27, 27, ICONID_NULL, 0, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal97)
SHOW_MAP_BODY(Skin98)
SHOW_MAP_BODY(Icon99)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal97, 272, 148, 299, 175)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_StaticICN_FileFilm8)
SHOW_MAP_BODY(Normal97)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_StaticICN_FileFilm8)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_StaticICN_FileFilm8, ICON_FILE_VIDEO)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_StaticICN_FileFilm8, 0, 272, 148, 299, 175)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_ITEM_RECT(CMD_Rectangle, Skin102Rect, 0, 0, 91, 25, 0, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Skin102)
SHOW_MAP_BODY(Skin102Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Skin102, 0, 0, 91, 25)

SHOW_ITEM_TEXT(CMD_Text | CMD_ITEM, Text104, 1, 0, 90, 27, STRID_NULL, 0, 1280, 0, 0, 2, 1, 1, 256, 0, 0, 0, 0, 0, 0)
SHOW_MAP_BEGIN(Normal101)
SHOW_MAP_BODY(Skin102)
SHOW_MAP_BODY(Text104)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group, Normal101, 197, 212, 288, 237)

SHOW_MAP_BEGIN(UIFlowWndPlayThumb_ThumbID)
SHOW_MAP_BODY(Normal101)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb_ThumbID)
CREATE_STATIC_DATA(UIFlowWndPlayThumb_ThumbID, STRID_MODE)
CREATE_STATIC_CTRL(UIFlowWndPlayThumb_ThumbID, 0, 197, 212, 288, 237)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndPlayThumb)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndPlayThumb)
DECLARE_CTRL_LIST(UIFlowWndPlayThumb)
CREATE_CTRL(UIFlowWndPlayThumb, UIFlowWndPlayThumb, CTRL_WND, NULL, 0, 0, 0, 319, 239)
#endif
