//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAY_H
#define UIFLOWWNDPLAY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayCtrl;//Panel type

extern VControl UIFlowWndPlay_TabNaviCtrl;//Tab type

typedef enum {
	UIFlowWndPlay_TabNavi_ButtonPlay,
	UIFlowWndPlay_TabNavi_ButtonLeft,
	UIFlowWndPlay_TabNavi_ButtonRight,
	UIFlowWndPlay_TabNavi_ButtonUp,
	UIFlowWndPlay_TabNavi_ButtonDown,
	UIFlowWndPlay_TabNavi_MAX
} UIFlowWndPlay_TabNavi_Setting;

extern VControl ButtonPlayCtrl;//Button type

extern VControl ButtonLeftCtrl;//Button type

extern VControl ButtonRightCtrl;//Button type

extern VControl ButtonUpCtrl;//Button type

extern VControl ButtonDownCtrl;//Button type

extern VControl UIFlowWndPlay_StaticICN_DSCModeCtrl;//Static type

extern VControl UIFlowWndPlay_StatusICN_FlashCtrl;//Status type

typedef enum {
	UIFLOW_PLAY_DISP_ID_1 = 0,
	UIFLOW_PLAY_DISP_ID_2,
	UIFLOW_PLAY_DISP_ID_MAX,
	ENUM_DUMMY4WORD(UIFLOW_PLAY_DISP_ID)
} UIFLOW_PLAY_DISP_ID;

typedef enum {
	UIFlowWndPlay_StatusICN_Flash_ICON_FLASH_AUTO,
	UIFlowWndPlay_StatusICN_Flash_ICON_FLASH_ON,
	UIFlowWndPlay_StatusICN_Flash_ICON_FLASH_RED_EYE,
	UIFlowWndPlay_StatusICN_Flash_ICON_FLASH_OFF,
	UIFlowWndPlay_StatusICN_Flash_MAX
} UIFlowWndPlay_StatusICN_Flash_Setting;

extern VControl UIFlowWndPlay_StatusICN_EVCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M2P0,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M1P6,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M1P3,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M1P0,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M0P6,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_M0P3,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P0P0,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P0P3,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P0P6,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P1P0,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P1P3,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P1P6,
	UIFlowWndPlay_StatusICN_EV_ICON_EV_P2P0,
	UIFlowWndPlay_StatusICN_EV_MAX
} UIFlowWndPlay_StatusICN_EV_Setting;

extern VControl UIFlowWndPlay_StaticTXT_SizeCtrl;//Static type

extern VControl UIFlowWndPlay_StatusICN_WBCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_WB_ICON_WB_AUTO,
	UIFlowWndPlay_StatusICN_WB_ICON_WB_DAYLIGHT,
	UIFlowWndPlay_StatusICN_WB_ICON_WB_CLOUDY,
	UIFlowWndPlay_StatusICN_WB_ICON_WB_TUNGSTEN,
	UIFlowWndPlay_StatusICN_WB_ICON_WB_FLUORESCENT,
	UIFlowWndPlay_StatusICN_WB_MAX
} UIFlowWndPlay_StatusICN_WB_Setting;

extern VControl UIFlowWndPlay_StatusICN_QualityCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_Quality_ICON_QUALITY_FINE,
	UIFlowWndPlay_StatusICN_Quality_ICON_QUALITY_NORMAL,
	UIFlowWndPlay_StatusICN_Quality_ICON_QUALITY_BASIC,
	UIFlowWndPlay_StatusICN_Quality_MAX
} UIFlowWndPlay_StatusICN_Quality_Setting;

extern VControl UIFlowWndPlay_StatusICN_SharpnessCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_Sharpness_ICON_SHARPNESS_HIGH,
	UIFlowWndPlay_StatusICN_Sharpness_ICON_SHARPNESS_MED,
	UIFlowWndPlay_StatusICN_Sharpness_ICON_SHARPNESS_LOW,
	UIFlowWndPlay_StatusICN_Sharpness_MAX
} UIFlowWndPlay_StatusICN_Sharpness_Setting;

extern VControl UIFlowWndPlay_StatusICN_StorageCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_Storage_ICON_INTERNAL_FLASH,
	UIFlowWndPlay_StatusICN_Storage_ICON_SD_CARD,
	UIFlowWndPlay_StatusICN_Storage_MAX
} UIFlowWndPlay_StatusICN_Storage_Setting;

extern VControl UIFlowWndPlay_StatusICN_BatteryCtrl;//Status type

typedef enum {
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_FULL,
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_MED,
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_LOW,
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_EMPTY,
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_ZERO,
	UIFlowWndPlay_StatusICN_Battery_ICON_BATTERY_CHARGE,
	UIFlowWndPlay_StatusICN_Battery_MAX
} UIFlowWndPlay_StatusICN_Battery_Setting;

extern VControl UIFlowWndPlay_StaticTXT_FilenameCtrl;//Static type

extern VControl UIFlowWndPlay_StaticICN_ProtectCtrl;//Static type

extern VControl UIFlowWndPlay_StaticTXT_DateCtrl;//Static type

extern VControl UIFlowWndPlay_StaticTXT_TimeCtrl;//Static type

extern VControl UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl;//Static type

extern VControl UIFlowWndPlay_StaticTXT_LeftBtnCtrl;//Static type

extern VControl UIFlowWndPlay_StaticTXT_RightBtnCtrl;//Static type

//---------------------UIFlowWndPlayCtrl User Export---------------------------
#endif
