//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"
#include "UIFlowWndPlayMagnify.h"
#include "AppCommon.h"
#include "Audio.h"
#include "UICommon.h"
#include "UIFlow.h"
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
#include "SMediaPlayAPI.h"
#include "DCF.h"
#include "UIAppMoviePlay.h"
//#NT#2012/08/31#Calvin Chang -end
#include "UIAppPlay.h"
#include "UIPlayComm.h"
// Photo mode key mask
#include "FileDB.h"
#include "ImageApp_MoviePlay.h"
#include "ImageApp_Play.h"
#include "GxVideoFile.h"
//#NT#2016/03/03#Ben Wang -begin
#include "PrjCfg.h"
#include "AppDisp_MoviePlayView.h"
//#NT#Add debug message for script test.
#define THIS_DBGLVL         2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIFlowWndPlay
#define __DBGLVL__          ((THIS_DBGLVL>=PRJ_DBG_LVL)?THIS_DBGLVL:PRJ_DBG_LVL)
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"
///////////////////////////////////////////////////////////////////////////////
//#NT#2016/03/03#Ben Wang -end
#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      FLGKEY_KEY_MASK_NULL//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT

#define FULL_FILE_PATH_LEN      64

#define BROWSER_VIEW			ENABLE
//#define NMEDIAPLAY_ENABLE       DISABLE     ///< 1: NMediaPlay flow on, 0: SMediaPlay flow on

BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
UINT32         g_uiUIFlowWndPlayCurrentVolume   = AUDIO_VOL_5;
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
MOVIEPLAY_FILEPLAY_INFO gMovie_Play_Info        = {0};
FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;
//#NT#2012/08/31#Calvin Chang -end
BOOL           g_bUIFlowWndPlayScreenSave       = FALSE;

extern UINT32  g_DualVideo;

MOVIEPLAY_DISP_INFO  gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_MAX] = {
    //enable       disp_id       w     h      ratio     rotate_dir       vid_out		dev_id
	{TRUE, MOVIEPLAY_DISP_ID_1, 960,  240  ,  4 , 3  ,     0 ,     MOVIEPLAY_VID_OUT_1, DOUT1},
	{TRUE, MOVIEPLAY_DISP_ID_2, 960,  240  ,  4 , 3  ,     0 ,     MOVIEPLAY_VID_OUT_2, DOUT2},
};


//---------------------UIFlowWndPlayCtrl Function ---------------------------
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);
void UIFlowWndPlay_ConfigDispInfo(void);

//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_TabNavi)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_DSCMode)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Flash)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_EV)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Size)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_WB)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Quality)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Sharpness)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Storage)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Battery)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Date)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Time)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
#if defined(_KEY_METHOD_2KEY_)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_LeftBtn)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_RightBtn)
#endif
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeySelect(VControl *, UINT32, UINT32 *);
#if defined(_KEY_METHOD_4KEY_)
INT32 UIFlowWndPlay_OnKeyPrev(VControl *, UINT32, UINT32 *);
#endif
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_NEXT, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIFlowWndPlay_OnKeySelect)
#if defined(_KEY_METHOD_4KEY_)
EVENT_ITEM(NVTEVT_KEY_PREV, UIFlowWndPlay_OnKeyPrev)
#endif
EVENT_ITEM(NVTEVT_KEY_UP, UIFlowWndPlay_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN, UIFlowWndPlay_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT, UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN, UIFlowWndPlay_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT, UIFlowWndPlay_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_MENU, UIFlowWndPlay_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_DISPLAY, UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE, UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, UIFlowWndPlay_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY, UIFlowWndPlay_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_ENTER, UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK, UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH, UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC, UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_STORAGE_INIT, UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIFlowWndPlay_OnStorageChange)
EVENT_END

static void UIFlowWndPlay_CheckStatus(void)
{
	UINT32 uiStatus, uiCurrMode;
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
	PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

	//#NT#2017/10/18#Adam Su -begin
	//#NT#AUTO_TEST
	exam_msg("PB_WaitCommandFinish\r\n");
	//#NT#2017/10/18#Adam Su -end

	// Decode Error & Read Error
	if (uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE)) {
		if (uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG) {
			UINT32  uiBuffAddr, uiBuffSize;
			CHAR    chaFullName[64] = { 0 };

			PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
			PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
			PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
			SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
			FileDB_Refresh(0);//2016/04/11
			debug_msg("^RSMediaPlay_FileRecovery is skipped.\r\n");
			uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
			if (uiStatus == PB_STA_DONE) {
				return;
			}
		}
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);
	}
}

#if 0
static INT32 UIFlowWndPlay_OnExeUpKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiCurrMode;
	PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		if (uiCurrMode == PLAYMODE_PRIMARY && PB_WaitCommandFinish(PB_WAIT_INFINITE) == PB_STA_DONE) {
			Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
		}
		break;
	case PLB_ST_PLAY_MOV:
		if (g_uiUIFlowWndPlayCurrentVolume < AUDIO_VOL_7) {
			// Start to Play
			g_uiUIFlowWndPlayCurrentVolume++;
			Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 1, g_uiUIFlowWndPlayCurrentVolume);
			//Ux_SendEvent(&CustomMoviePlayObjCtrl,
			//             NVTEVT_EXE_STARTPLAY,
			//             2,
			//             g_uiUIFlowWndPlayCurrenSpeed,
			//             g_uiUIFlowWndPlayCurrenDirection);
			FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
		}
		break;

	}
	return NVTEVT_CONSUME;
}

static INT32 UIFlowWndPlay_OnExeDownKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiActKey;

	if (paramNum >= 1) {
		uiActKey = paramArray[0];
	} else {
		debug_msg("error parameter!!\r\n");
		return NVTEVT_CONSUME;
	}

	switch (uiActKey) {
	case NVTEVT_KEY_PRESS:
		switch (g_PlbData.State) {
		case PLB_ST_FULL:
			Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
			break;
		case PLB_ST_PLAY_MOV:
			if (g_uiUIFlowWndPlayCurrentVolume > AUDIO_VOL_MUTE) {
				// Start to Play
				g_uiUIFlowWndPlayCurrentVolume--;
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 1, g_uiUIFlowWndPlayCurrentVolume);
				//Ux_SendEvent(&CustomMoviePlayObjCtrl,
				//             NVTEVT_EXE_STARTPLAY,
				//             2,
				//             g_uiUIFlowWndPlayCurrenSpeed,
				//             g_uiUIFlowWndPlayCurrenDirection);
				FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
			}
			break;
		}
		break;
	}
	return NVTEVT_CONSUME;
}
#endif

INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiStatus;
	UINT32 uiFileNum = 0;
#if 1//(SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_KEEP);
		return NVTEVT_CONSUME;
	}
#endif
	g_bUIFlowWndPlayNoImgWndOpened = FALSE;

	PB_WaitCommandFinish(PB_WAIT_INFINITE);
	//After playback ready, point to the last file
	PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
//    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
	PB_OpenSpecFileBySeq(uiFileNum, TRUE);
	UIPlay_PlaySingle(PB_SINGLE_CURR);
	uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

	//disable video2 and enable video 1
	Display_ShowPreview();

	UpdateVdoWinForPB();

	if (uiStatus & PB_STA_NOIMAGE)
		//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
	{
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
		g_bUIFlowWndPlayNoImgWndOpened = TRUE;
	} else {
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		g_PlbData.State = PLB_ST_FULL;
		UxTab_SetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS, UIFlowWndPlay_TabNavi_ButtonPlay);
		UIFlowWndPlay_CheckStatus();
		FlowPB_UpdateIcons(1);
	}

	// Set mask key
	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		break;

	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		g_PlbData.State        = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

		ImageApp_MoviePlay_Close();
        if (gMovie_Play_Info.event_cb) {
			#if (NMEDIAPLAY_FUNC == DISABLE)
			gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
			#else //((NMEDIAPLAY_FUNC == ENABLE))
			gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
			#endif
		}

		if (g_bUIFlowWndPlayScreenSave) {
			GxPower_SetControl(GXPWR_CTRL_SLEEP_EN, TRUE);
		}

		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}
		break;
	}

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end
	//g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_NEXT_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
		{
			g_PlbData.VideoPBSpeed ++;

			Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

			if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_FWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
			}
			else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_BWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
			}
			else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
			{
				g_PlbData.State = PLB_ST_PLAY_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
			}

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if (NMEDIAPLAY_FUNC == DISABLE)
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
			ImageApp_MoviePlay_UpdateAll();
			#else //(NMEDIAPLAY_FUNC == ENABLE)
			UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_DISP_IDX, vdo_idx);
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection);
			#endif

			//FlowPB_IconDrawMovSpeed();
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		}
		break;
	case PLB_ST_PAUSE_MOV:
		Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_FORWARD);
		Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		break;
	default:
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
	case PLB_ST_FULL:
		Ux_SendEvent(&UIFlowWndPlay_TabNaviCtrl, NVTEVT_PREVIOUS_ITEM, 0);
		break;
	case PLB_ST_PLAY_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		if(g_PlbData.VideoPBSpeed > PLB_BWD_MOV_8x)
		{
			g_PlbData.VideoPBSpeed --;

			Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

			if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_FWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
			}
			else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
			{
				g_PlbData.State = PLB_ST_BWD_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;
			}
			else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
			{
				g_PlbData.State = PLB_ST_PLAY_MOV;
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
			}

			// Set speed and direction
			UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
			#if (NMEDIAPLAY_FUNC == DISABLE)
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
			ImageApp_MoviePlay_UpdateAll();
			#else //(NMEDIAPLAY_FUNC == ENABLE)
			UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
			ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_DISP_IDX, vdo_idx);
			ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection);
			#endif

			//FlowPB_IconDrawMovSpeed();
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		}
		break;
	case PLB_ST_PAUSE_MOV:
		Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
		ImageApp_MoviePlay_FilePlay_StepByStep(SMEDIAPLAY_DIR_BACKWARD);
		Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
		break;
	default:
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}
	switch (g_PlbData.State) {
		UINT32 Tabfocus;
	case PLB_ST_FULL:
		Tabfocus = UxTab_GetData(&UIFlowWndPlay_TabNaviCtrl, TAB_FOCUS);
		switch (Tabfocus) {
			char   pFilePath[FULL_FILE_PATH_LEN];
			UINT32 uiPBFileFmt;
			UINT32 uiPBFileSize = 0;
		case UIFlowWndPlay_TabNavi_ButtonPlay:
			PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
                GXVIDEO_INFO VidInfo = {0};
                SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						debug_msg("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				debug_msg("Play File Path = %s\r\n", pFilePath);

				//#NT#2017/11/13#Adam Su -begin
				//#NT#AUTO_TEST
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/13#Adam Su -end

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

				if (!gphUIFlowMovPlay_Filehdl) {
					debug_msg("UIFlowWndPlay_OnKeySelect: Can't open Video file!\r\n");
					break;
				}
				//#NT#2012/10/23#Philex Lin - begin
				// disable auto power off/USB detect timer
				// disable key tone flag
				KeyScan_EnableMisc(FALSE);
				//#NT#2012/10/23#Philex Lin - end

				UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

				ImageApp_Play_Close();

				#if (VDO_USE_COPY_BUFFER == ENABLE)
				VdoOut_SetSkipAllocTemp(TRUE);
				#endif

				g_bUIFlowWndPlayScreenSave = GxPower_GetControl(GXPWR_CTRL_SLEEP_EN);

				if (g_bUIFlowWndPlayScreenSave) {
					GxPower_SetControl(GXPWR_CTRL_SLEEP_EN, FALSE);
				}

                // Config file play info
				gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
				gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
				gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
				gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb    = Play_MovieCB;
				#else //(NMEDIAPLAY_FUNC == ENABLE)
				gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
				#endif

                // Config max mem info
                PB_GetParam(PBPRMID_INFO_VDO, (UINT32*) &VidInfo);
                if (uiPBFileFmt & PBFMT_TS) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
                } else if (uiPBFileFmt & PBFMT_MP4) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
                }
                SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
                SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
                SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
                SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
                SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
                SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
                gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

				ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

				// Config rotation info
				UIFlowWndPlay_ConfigDispInfo();

				//flush event first
				Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);

				//stop scan
				//SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
				SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

				ImageApp_MoviePlay_Open();
				#if (NMEDIAPLAY_FUNC == ENABLE)
				ImageApp_MoviePlay_Start();
				#endif

				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
				FlowPB_UpdateIcons(0);
				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawLeftBtn(TRUE);
				FlowPB_IconDrawRightBtn(TRUE);
				FlowPB_IconDrawMovPlayTime(TRUE);
			} else {
				g_PlbData.State = PLB_ST_MAGNIFY;
				FlowPB_UpdateIcons(0);
				FlowPB_IconDrawLeftBtn(TRUE);

				//#NT#2017/11/17#Adam Su -begin
				//#NT#AUTO_TEST
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/17#Adam Su -end
			}
			break;
		case UIFlowWndPlay_TabNavi_ButtonLeft:
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
			UIPlay_PlaySingle(PB_SINGLE_PREV);
			FlowPB_UpdateIcons(1);
			UIFlowWndPlay_CheckStatus();
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			break;
		case UIFlowWndPlay_TabNavi_ButtonRight:
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
			UIPlay_PlaySingle(PB_SINGLE_NEXT);
			FlowPB_UpdateIcons(1);
			UIFlowWndPlay_CheckStatus();
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			break;
		case UIFlowWndPlay_TabNavi_ButtonUp:
			//Ux_OpenWindow(&UIMenuWndPlayDelCtrl, 0);
			//Ux_OpenWindow((VControl *)(&UIMenuWndPlayConfirmDelCtrl), 1, UIMenuWndPlayConfirmDel_StatusText_STRID_ERASE_THIS);
			Ux_OpenWindow(&MenuCommonConfirmCtrl, 1, IDM_DELETE_THIS);
			break;
		case UIFlowWndPlay_TabNavi_ButtonDown:
			g_PlbData.State = PLB_ST_MENU;
			// Reset specific menu items
			SysSetFlag(FL_PROTECT, PROTECT_ONE);
			// Set Tab menu to Playback menu
			// Open common item menu
			Ux_OpenWindow(&MenuCommonItemCtrl, 0);
			Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
			break;
		default:
			break;
		}
		break;
	case PLB_ST_MAGNIFY:
		g_PlbData.State = PLB_ST_FULL;
		FlowPB_UpdateIcons(1);
		break;
	case PLB_ST_PLAY_MOV:
	case PLB_ST_PAUSE_MOV:
		g_PlbData.State        = PLB_ST_FULL;
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

		ImageApp_MoviePlay_Close();
		if (gMovie_Play_Info.event_cb) {
			#if (NMEDIAPLAY_FUNC == DISABLE)
			gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
			#else //((NMEDIAPLAY_FUNC == ENABLE))
			gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
			#endif
		}

		if (g_bUIFlowWndPlayScreenSave) {
			GxPower_SetControl(GXPWR_CTRL_SLEEP_EN, TRUE);
		}

		ImageApp_Play_Open();

		//#NT#2012/10/23#Philex Lin - begin
		// enable auto power off/USB detect timer
		// enable key tone flag
		KeyScan_EnableMisc(TRUE);
		//#NT#2012/10/23#Philex Lin - end

		// stop scan
		//if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
		//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

		if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
			SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
		}


		if (gphUIFlowMovPlay_Filehdl) {
			FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
			gphUIFlowMovPlay_Filehdl = NULL;
		}

		// Play 1st video frame image
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		//#NT#2012/08/31#Calvin Chang -end

		FlowPB_UpdateIcons(1);

		break;
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		//#NT#2012/10/23#Philex Lin - begin
        // disable auto power off/USB detect timer
        // disable key tone flag
        KeyScan_EnableMisc(FALSE);
        //#NT#2012/10/23#Philex Lin - end

		// Set to Normal Play
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

        // Start Play
        #if (NMEDIAPLAY_FUNC == DISABLE)
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
		ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
		ImageApp_MoviePlay_UpdateAll();
		#else //(NMEDIAPLAY_FUNC == ENABLE)
		UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_DISP_IDX, vdo_idx);
		ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection);
		#endif

        /*if (KeyScan_GetPlugDev()!=PLUG_HDMI)
        {
            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
        }*/

        g_PlbData.State = PLB_ST_PLAY_MOV;

        //Update UI
        /*FlowPB_IconDrawMovPlay(TRUE);
        FlowPB_IconDrawMovFwd(TRUE);
        FlowPB_IconDrawMovBwd(TRUE);
        FlowPB_IconDrawMovSpeed();*/
	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32 uiStatus;

	//#NT#2012/12/27#Hideo Lin -begin
	//#NT#Fix close child window hang up as card removed
	if (Ux_IsForceCloseWindow()) {
		return NVTEVT_CONSUME;
	}
	//#NT#2012/12/27#Hideo Lin -end

	if (paramNum > 0) {
		//Return from thumbnail, magnify or delete mode and play current image again.
		switch (paramArray[0]) {
		case NVTRET_THUMBNAIL:
		case NVTRET_MAGNIFY:
			UIPlay_PlaySingle(PB_SINGLE_CURR);
			FlowPB_UpdateIcons(1);
			UIFlowWndPlay_CheckStatus();
			break;
		case NVTRET_DELETE:
		case NVTRET_DELETEALL:
			uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

			if (uiStatus & PB_STA_NOIMAGE)
				//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
			{
				if (!g_bUIFlowWndPlayNoImgWndOpened) {
					Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
					g_bUIFlowWndPlayNoImgWndOpened = TRUE;
				}
			} else {
				UIPlay_PlaySingle(PB_SINGLE_CURR);
				FlowPB_UpdateIcons(1);
				UIFlowWndPlay_CheckStatus();
			}
			break;
		case NVTRET_ENTER_MENU:
			// Reset specific menu items
			SysSetFlag(FL_PROTECT, PROTECT_ONE);
			// Open common item menu
			Ux_OpenWindow(&MenuCommonItemCtrl, 0);
			g_bUIFlowWndPlayNoImgWndOpened = FALSE;
			break;
		case NVTRET_WARNING:
			Ux_PostEvent(paramArray[1], 0);
			break;
		}
	} else {
		UIPlay_PlaySingle(PB_SINGLE_CURR);
		uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
		if (uiStatus & PB_STA_NOIMAGE)
			//if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
		{
			if (!g_bUIFlowWndPlayNoImgWndOpened) {
				Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_NO_IMAGE, FLOWWRNMSG_TIMER_2SEC);
				g_bUIFlowWndPlayNoImgWndOpened = TRUE;
			} else {
				g_PlbData.State = PLB_ST_MENU;
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
				// Reset specific menu items
				SysSetFlag(FL_PROTECT, PROTECT_ONE);
				// Open common item menu
				Ux_OpenWindow(&MenuCommonItemCtrl, 0);
				Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
			}
		} else { //file error
			//UIPlay_PlaySingle(PB_SINGLE_CURR);
			FlowPB_UpdateIcons(1);
			//UIFlowWndPlay_CheckStatus();
		}
	}
	g_PlbData.State = PLB_ST_FULL;

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable sound key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

	// set mask key
	//Ux_FlushEvent();
	Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	static volatile BOOL bBatteryOn = FALSE;

	UxState_SetData(&UIFlowWndPlay_StatusICN_BatteryCtrl, STATE_CURITEM, GetBatteryLevel());
	if (KeyScan_IsACIn()) {
		bBatteryOn = !bBatteryOn;
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, bBatteryOn);
	} else {
		UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl, TRUE);
	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	switch (g_PlbData.State) {
	case PLB_ST_PLAY_MOV:
		//Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
		ImageApp_MoviePlay_FilePlay_Pause();
		g_PlbData.State = PLB_ST_PAUSE_MOV;
		FlowPB_IconDrawRightBtn(TRUE);
		//#NT#2012/10/23#Philex Lin - begin
		// enable auto power off/USB detect timer
		// enable sound key tone flag
		KeyScan_EnableMisc(TRUE);
		//#NT#2012/10/23#Philex Lin - end
		break;
	case PLB_ST_PAUSE_MOV:
		//#NT#2012/10/23#Philex Lin - begin
		// disable auto power off/USB detect timer
		// disable key tone flag
		KeyScan_EnableMisc(FALSE);
		//#NT#2012/10/23#Philex Lin - end
		// Start to Play
		//set movie volumn again to avoid volumn changed by beep sound
		Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
		ImageApp_MoviePlay_FilePlay_Resume();
		g_PlbData.State = PLB_ST_PLAY_MOV;
		FlowPB_IconDrawRightBtn(TRUE);
		break;
	#if (BROWSER_VIEW == ENABLE)
	case PLB_ST_FULL:
		Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
		break;
	#endif
	default:
		break;
	}

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
	g_PlbData.State        = PLB_ST_FULL;
	g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
	UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
	g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

	ImageApp_MoviePlay_Close();
	if (gMovie_Play_Info.event_cb) {
		#if (NMEDIAPLAY_FUNC == DISABLE)
		gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
		#else //((NMEDIAPLAY_FUNC == ENABLE))
		gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
		#endif
	}

	if (g_bUIFlowWndPlayScreenSave) {
		GxPower_SetControl(GXPWR_CTRL_SLEEP_EN, TRUE);
	}

	ImageApp_Play_Open();

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

	// stop scan
	//if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

	if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID) == 0) {
		SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);
	}


	if (gphUIFlowMovPlay_Filehdl) {
		FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
		gphUIFlowMovPlay_Filehdl = NULL;
	}

	// Play 1st video frame image
	UIPlay_PlaySingle(PB_SINGLE_CURR);
	//#NT#2012/08/31#Calvin Chang -end

	FlowPB_UpdateIcons(1);
	//#NT#2016/03/03#Ben Wang -begin
	//#NT#Add debug message for script test.
	DBG_TEST("OnMovieFinish\r\n");
	//#NT#2016/11/10#Niven Cho -begin
	//#NT#AUTO_TEST
	exam_msg("OnMovieFinish\r\n");
	//#NT#2016/11/10#Niven Cho -end
	//#NT#2016/03/03#Ben Wang -end

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	FlowPB_IconDrawMovPlayTime(TRUE);

	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}

void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
	switch (uiChangeSpeedLevel) {
	default:
	case PLB_FWD_MOV_1x:
	case PLB_BWD_MOV_1x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_NORMAL;
		break;

	case PLB_FWD_MOV_2x:
	case PLB_BWD_MOV_2x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_2X;
		break;

	case PLB_FWD_MOV_4x:
	case PLB_BWD_MOV_4x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_4X;
		break;

	case PLB_FWD_MOV_8x:
	case PLB_BWD_MOV_8x:
		g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_8X;
		break;

	}
}

static void UIFlowWndPlay_SetDispParam(MOVIEPLAY_DISP_INFO *p_disp_info, BOOL en)
{
	USIZE device_ratio, src_size;

	if (en == TRUE) { // use dev_id when enable
		device_ratio = GxVideo_GetDeviceAspect(p_disp_info->dev_id);
	} else {
		device_ratio = GxVideo_GetDeviceAspect(DOUT1);
	}
	PB_GetParam(PBPRMID_SRC_SIZE, (UINT32 *) &src_size); // get source image size from playback

	p_disp_info->enable			= en;
	p_disp_info->width			= src_size.w;
	p_disp_info->height			= src_size.h;
	p_disp_info->width_ratio	= device_ratio.w;
	p_disp_info->height_ratio	= device_ratio.h;
	p_disp_info->rotate_dir		= SysVideo_GetDirbyID(p_disp_info->dev_id);

	ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_DISP_INFO, (UINT32)p_disp_info);
}

void UIFlowWndPlay_ConfigDispInfo(void)
{
	//MOVIEPLAY_DISP_INFO	*p_disp_info = NULL;

#if (DISPLAY2_FUNC == ENABLE)
	if (g_DualVideo == DISPLAY_1) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], FALSE);
	} else if (g_DualVideo == DISPLAY_2) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], FALSE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	} else if (g_DualVideo == (DISPLAY_1|DISPLAY_2)) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	}
#else
	UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
#endif

}

//----------------------UIFlowWndPlay_TabNaviCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_TabNavi)
EVENT_END

//----------------------ButtonPlayCtrl Event---------------------------
EVENT_BEGIN(ButtonPlay)
EVENT_END

//----------------------ButtonLeftCtrl Event---------------------------
EVENT_BEGIN(ButtonLeft)
EVENT_END

//----------------------ButtonRightCtrl Event---------------------------
EVENT_BEGIN(ButtonRight)
EVENT_END

//----------------------ButtonUpCtrl Event---------------------------
EVENT_BEGIN(ButtonUp)
EVENT_END

//----------------------ButtonDownCtrl Event---------------------------
EVENT_BEGIN(ButtonDown)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_DSCModeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_DSCMode)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_FlashCtrl Event---------------------------
INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Flash)
EVENT_ITEM(NVTEVT_KEY_RIGHT, UIFlowWndPlay_StatusICN_Flash_OnKeyRight)
EVENT_END

INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);
	return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_EV)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SizeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Size)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_WBCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_WB)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_QualityCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Quality)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_SharpnessCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Sharpness)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Storage)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Battery)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_DateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Date)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_TimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Time)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_LeftBtnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_LeftBtn)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_RightBtnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_RightBtn)
EVENT_END

