//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPLAYMAGNIFY_H
#define UIFLOWWNDPLAYMAGNIFY_H

#include "UIFramework.h"

extern VControl UIFlowWndPlayMagnifyCtrl;//Panel type

extern VControl UIFlowWndPlayMagnify_StaticTXT_DZoomCtrl;//Static type

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirUpCtrl;//Static type

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirDownCtrl;//Static type

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirRightCtrl;//Static type

extern VControl UIFlowWndPlayMagnify_StaticIcon_DirLeftCtrl;//Static type

#endif
