//This source code is generated by UI Designer Studio.

#include <stdio.h>
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "AudioTestWndRes.c"
#include "AudioTestWnd.h"
#include "MovieRecTestWnd.h"
#include "MoviePlayTestWnd.h"
#include "BurnInWnd.h"
#include "PrjCfg.h"
#include "GxTimer.h"
#include "UIFlow.h"
#if !defined(_GSensor_None_)
#include "GSensor.h"
#endif
#include "UIBackgroundObj.h"
#include "FileDB.h"

#define __MODULE__          AudioTest
#define __DBGLVL__          1 // 0=OFF, 1=ERROR, 2=TRACE
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"

enum _AUDIOTEST_STATE
{
    AUDIOTEST_ST_STANDBY,   // standby
    AUDIOTEST_ST_REC,       // movie recording test
    AUDIOTEST_ST_PLAY       // movie play test
};

#define AUDIOTEST_REC_TIME      3 // test 3 seconds
#define AUDIOTEST_AUTO_START    DISABLE

//---------------------AudioTestWndCtrl Debug Definition -----------------------------
#define _AUDIOTESTWND_ERROR_MSG        1
#define _AUDIOTESTWND_TRACE_MSG        0

#if (_AUDIOTESTWND_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define AudioTestWndErrMsg(...)            debug_msg ("^R AudioTestWnd: "__VA_ARGS__)
#else
#define AudioTestWndErrMsg(...)
#endif

#if (_AUDIOTESTWND_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define AudioTestWndTraceMsg(...)          debug_msg ("^B AudioTestWnd: "__VA_ARGS__)
#else
#define AudioTestWndTraceMsg(...)
#endif

//---------------------AudioTestWndCtrl Global Variables -----------------------------
static BOOL     g_bAudioTestWndOpen = FALSE;
static UINT32   g_uiAudioTestState = AUDIOTEST_ST_REC;
static UINT32   g_uiAudioTestTimer = NULL_TIMER;

//---------------------AudioTestWndCtrl Prototype Declaration  -----------------------

//---------------------AudioTestWndCtrl Public API  ----------------------------------
void AudioTest_DrawData(BOOL bClear)
{
    if (g_bAudioTestWndOpen)
    {
        CHAR    cDataStr[30];
        //#NT#2016/10/05#Brain Yen -begin
        //#NT# Coverity CID 67997,67998,67999
        //INT32   iX, iY, iZ;
        INT32   iX=0, iY=0, iZ=0;
        //#NT#2016/10/05#Brain Yen -end
        memset((void *)cDataStr, 0, sizeof(cDataStr));
#if !defined(_GSensor_None_)
        GSensor_GetAxisValue(&iX, &iY, &iZ);
#endif
        snprintf(cDataStr, sizeof(cDataStr), "g-sensor & Audio Test");
        UI_DrawOsdString(cDataStr, 12, 12, CLRID_IDX_SKYBLUE, bClear);
        snprintf(cDataStr, sizeof(cDataStr), "g: x %d, y %d, z %d   ", iX, iY, iZ);
        UI_DrawOsdString(cDataStr, 12, 12+30*3, CLRID_IDX_WHITE, bClear);
    }
}

void AudioTest_DrawTestResult(BOOL bClear)
{
    if (g_bAudioTestWndOpen)
    {
        CHAR    cDataStr[32];

        memset((void *)cDataStr, 0, sizeof(cDataStr));
        snprintf(cDataStr, sizeof(cDataStr), "Test Finished!");
        UI_DrawOsdString(cDataStr, 12, 12+30, CLRID_IDX_GREEN, bClear);
        snprintf(cDataStr, sizeof(cDataStr), "Press shutter key to test again");
        UI_DrawOsdString(cDataStr, 12, 12+30*2, CLRID_IDX_WHITE, bClear);
    }
}

//---------------------AudioTestWndCtrl Private API  ---------------------------------
#if !AUDIOTEST_AUTO_START
static void AudioTest_DrawTestStart(BOOL bClear)
{
    if (g_bAudioTestWndOpen)
    {
        CHAR    cDataStr[32];

        memset((void *)cDataStr, 0, sizeof(cDataStr));
        snprintf(cDataStr, sizeof(cDataStr), "Status: Live View     ");
        UI_DrawOsdString(cDataStr, 12, 12+30, CLRID_IDX_WHITE, bClear);
        snprintf(cDataStr, sizeof(cDataStr), "Press shutter key to start test");
        UI_DrawOsdString(cDataStr, 12, 12+30*2, CLRID_IDX_WHITE, bClear);
    }
}
#endif

//---------------------AudioTestWndCtrl Control List---------------------------
CTRL_LIST_BEGIN(AudioTestWnd)
CTRL_LIST_END

//----------------------AudioTestWndCtrl Event---------------------------
INT32 AudioTestWnd_OnOpen(VControl *, UINT32, UINT32 *);
INT32 AudioTestWnd_OnClose(VControl *, UINT32, UINT32 *);
INT32 AudioTestWnd_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 AudioTestWnd_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 AudioTestWnd_OnTimer(VControl *, UINT32, UINT32 *);
INT32 AudioTestWnd_OnBackgroundDone(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(AudioTestWnd)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,AudioTestWnd_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,AudioTestWnd_OnClose)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,AudioTestWnd_OnKeyShutter2)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,AudioTestWnd_OnChildClose)
EVENT_ITEM(NVTEVT_TIMER,AudioTestWnd_OnTimer)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE,AudioTestWnd_OnBackgroundDone)
EVENT_END

INT32 AudioTestWnd_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_bAudioTestWndOpen = TRUE;
    //g_uiAudioTestState = AUDIOTEST_ST_REC;
    g_uiAudioTestState = AUDIOTEST_ST_STANDBY;

#if !defined(_GSensor_None_)
    GSensor_open();
#endif

    if (g_uiAudioTestTimer == NULL_TIMER)
    {
        g_uiAudioTestTimer = GxTimer_StartTimer(TIMER_ONE_SEC, NVTEVT_1SEC_TIMER, CONTINUE);
    }

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    Ux_Redraw();
    BurnIn_DrawStatus("Delete files...", CLRID_IDX_ORANGE, TRUE);
    BKG_PostEvent(NVTEVT_BKW_DELALL);

    return NVTEVT_CONSUME;
}

INT32 AudioTestWnd_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_uiAudioTestTimer != NULL_TIMER)
    {
        GxTimer_StopTimer(&g_uiAudioTestTimer);
    }

    g_bAudioTestWndOpen = FALSE;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 AudioTestWnd_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiKeyAct;

    uiKeyAct = paramNum ? paramArray[0] : 0;

    if (uiKeyAct != NVTEVT_KEY_PRESS)
        return NVTEVT_CONSUME;

    if (g_uiAudioTestState != AUDIOTEST_ST_REC)
    {
        g_uiAudioTestState = AUDIOTEST_ST_REC;
        MovieRecTestWnd_SetRecTime(AUDIOTEST_REC_TIME); // set movie recording time
        MovieRecTestWnd_SetAudioGain(100); // set audio gain to max
        Ux_OpenWindow((VControl *)(&MovieRecTestWndCtrl), 0);
    }
    return NVTEVT_CONSUME;
}

INT32 AudioTestWnd_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch (g_uiAudioTestState)
    {
    case AUDIOTEST_ST_REC:
        g_uiAudioTestState = AUDIOTEST_ST_PLAY;
        MoviePlayTestWnd_SetAudioVolume(100); // set audio volume to max
        MoviePlayTestWnd_SetPlayReserveSec(0);
        Ux_OpenWindow((VControl *)(&MoviePlayTestWndCtrl), 0);
        break;

    case AUDIOTEST_ST_PLAY:
        Ux_Redraw();
        AudioTest_DrawData(TRUE);
        AudioTest_DrawTestResult(TRUE);
        break;

    default:
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 AudioTestWnd_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiEvent;

    uiEvent = paramNum ? paramArray[0] : 0;

    switch(uiEvent)
    {
    case NVTEVT_1SEC_TIMER:
        AudioTest_DrawData(TRUE);
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 AudioTestWnd_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT  event;

    event = paramArray[ONDONE_PARAM_INDEX_CMD];

    switch(event)
    {
    case NVTEVT_BKW_DELALL:
        FileDB_Refresh(0);
        #if AUDIOTEST_AUTO_START
        Ux_PostEvent(NVTEVT_KEY_SHUTTER2, 1, NVTEVT_KEY_PRESS); // post shutter2 event to start recording
        #else
        AudioTest_DrawTestStart(TRUE);
        #endif
        break;

    default:
        break;
    }

    return NVTEVT_CONSUME;
}

