//This source code is generated by UI Designer Studio.

#include <stdio.h>
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "BurnInWndRes.c"
#include "BurnInWnd.h"
#include "KeyTestWnd.h"
#include "MovieRecTestWnd.h"
#include "MoviePlayTestWnd.h"
#include "LCDTestWnd.h"
#include "LEDTestWnd.h"
#include "AudioTestWnd.h"
#include "PrjCfg.h"
#include "FileSysTsk.h"
#include "UIBackgroundObj.h"
#include "FileDB.h"
#include "DxWiFi.h"
#include "AppControl.h"
#include "SxTimer.h"
#include "UIInfo.h"
#include "SysCommon.h"

#define __MODULE__          BurnIn
#define __DBGLVL__          1 // 0=OFF, 1=ERROR, 2=TRACE
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"

enum _BURNIN_STATE
{
    BURNIN_ST_KEY,  // key test
    BURNIN_ST_LCD,  // LCD test
    BURNIN_ST_LED,  // LED test
    BURNIN_ST_AUD,  // audio test
    BURNIN_ST_REC,  // movie recording test
    BURNIN_ST_PLAY  // movie play test
};

#define BURNIN_REC_TIME     180 // record 180 seconds
#define LCD_TEST_IN_LOOP    ENABLE

//
// Burn in start -> Key Test -> LCD Test -> LED Test -> Audio Test -> Movie Record -> Movie Play --
//                                 ^                                                               |
//                                 |                                                               |
//                                  ---------------------------------------------------------------
//

//---------------------BurnInWndCtrl Debug Definition -----------------------------
#define _BURNINWND_ERROR_MSG        1
#define _BURNINWND_TRACE_MSG        0

#if (_BURNINWND_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define BurnInWndErrMsg(...)            debug_msg ("^R BurnInWnd: "__VA_ARGS__)
#else
#define BurnInWndErrMsg(...)
#endif

#if (_BURNINWND_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define BurnInWndTraceMsg(...)          debug_msg ("^B BurnInWnd: "__VA_ARGS__)
#else
#define BurnInWndTraceMsg(...)
#endif

extern int SX_TIMER_DET_GSENSOR_ID;

//---------------------BurnInWndCtrl Global Variables -----------------------------
static BOOL     g_bBurnInWndOpen = FALSE;
static UINT32   g_uiBurnInState = BURNIN_ST_KEY;
static UINT32   g_uiLoopCountMax = 20; // default do 20 times
static UINT32   g_uiLoopCount = 0;

//---------------------BurnInWndCtrl Prototype Declaration  -----------------------

//---------------------BurnInWndCtrl Public API  ----------------------------------
void BurnIn_DrawLoopCount(BOOL bClear)
{
    if (g_bBurnInWndOpen)
    {
        CHAR cLoopCountStr[20];

        memset((void *)cLoopCountStr, 0, sizeof(cLoopCountStr));
        snprintf(cLoopCountStr, sizeof(cLoopCountStr), "Loop: %d   ", g_uiLoopCount);
        UI_DrawOsdString(cLoopCountStr, 12, 12, CLRID_IDX_WHITE, bClear);
    }
}

void BurnIn_DrawStatus(CHAR *pStr, UINT32 uiColor, BOOL bClear)
{
    CHAR cStatusStr[40];

    memset((void *)cStatusStr, 0, sizeof(cStatusStr));
    snprintf(cStatusStr, sizeof(cStatusStr), "Status: %s   ", pStr);
    UI_DrawOsdString(cStatusStr, 12, 12+30, uiColor, bClear);
}

void BurnIn_DrawTime(UINT32 uiTime)
{
    CHAR cTimeStr[20];

    memset((void *)cTimeStr, 0, sizeof(cTimeStr));
    snprintf(cTimeStr, sizeof(cTimeStr), "%02d:%02d:%02d  ", uiTime/3600, (uiTime%3600)/60, (uiTime%3600)%60);
    UI_DrawOsdString(cTimeStr, 12, 12+30*2, CLRID_IDX_WHITE, TRUE);
}

void BurnIn_DrawTips(CHAR *pStr)
{
    CHAR cTipsStr[40];

    memset((void *)cTipsStr, 0, sizeof(cTipsStr));
    snprintf(cTipsStr, sizeof(cTipsStr), "%s   ", pStr);
    UI_DrawOsdString(cTipsStr, 12, 12+30*2, CLRID_IDX_WHITE, TRUE);
}

//---------------------BurnInWndCtrl Private API  ---------------------------------
static void BurnIn_CheckLoopSetting(void)
{
    #define BURNIN_SETTING_SIZE 30
    #define BURNIN_LOOP_STRING  "loop="

    UINT32      uiReadSize = BURNIN_SETTING_SIZE;
    UINT32      uiLoopCount;
    //#NT#2016/10/05#Brain Yen -begin
    //#NT#Coverity CID 67996
    //CHAR        cDataBuf[BURNIN_SETTING_SIZE], *pCh;
    CHAR        cDataBuf[BURNIN_SETTING_SIZE]={0}, *pCh;
    //#NT#2016/10/05#Brain Yen -end
    FST_FILE    pFile;

    pFile = FileSys_OpenFile("A:\\Burn-In.CAL", FST_OPEN_READ);
    if (pFile)
    {
        FileSys_ReadFile(pFile, (UINT8 *)cDataBuf, &uiReadSize, 0, NULL);
        FileSys_CloseFile(pFile);

        DBG_DUMP("Read size %d\r\n", uiReadSize);
        if (uiReadSize)
        {
            pCh = strstr(cDataBuf, BURNIN_LOOP_STRING);
            sscanf(pCh + sizeof(BURNIN_LOOP_STRING) - 1, "%d", &uiLoopCount);
            g_uiLoopCountMax = uiLoopCount;
            DBG_DUMP("^Y Loop Count = %d, size %d\r\n", uiLoopCount, sizeof(BURNIN_LOOP_STRING));
        }
    }
    else
    {
        DBG_ERR("Open burn in setting file error!\r\n");
    }
}

//---------------------BurnInWndCtrl Control List---------------------------
CTRL_LIST_BEGIN(BurnInWnd)
CTRL_LIST_END

//----------------------BurnInWndCtrl Event---------------------------
INT32 BurnInWnd_OnOpen(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnClose(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnKeyPower(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 BurnInWnd_OnBackgroundDone(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(BurnInWnd)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,BurnInWnd_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,BurnInWnd_OnClose)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,BurnInWnd_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_PREV,BurnInWnd_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_NEXT,BurnInWnd_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_SELECT,BurnInWnd_OnKeyPower)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,BurnInWnd_OnChildClose)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE,BurnInWnd_OnBackgroundDone)
EVENT_END

INT32 BurnInWnd_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_bBurnInWndOpen = TRUE;
    g_uiBurnInState = BURNIN_ST_KEY;
    g_uiLoopCount = 0;

    BurnIn_CheckLoopSetting();

    Reset_MenuInfo();

    GxPower_SetControl(GXPWR_CTRL_AUTOPOWEROFF_RESET,0);
    GxPower_SetControl(GXPWR_CTRL_SLEEP_RESET,0);
    SxTimer_SetFuncActive(SX_TIMER_DET_SLEEP_ID,FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_AUTOPOWEROFF_ID,FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_MODE_ID,FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_GSENSOR_ID, FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_BATT_ID, FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_MODE_ID, FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_TV_ID, FALSE);
#if (LED_FUNCTION == ENABLE)
    SxTimer_SetFuncActive(SX_TIMER_DET_LED_ID, FALSE);
#endif
    SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_USB_ID, FALSE);
#if (FLASHLIGHT_FUNCTION == ENABLE)
    SxTimer_SetFuncActive(SX_TIMER_DET_FLASH_ID, FALSE);
    SxTimer_SetFuncActive(SX_TIMER_DET_RECHARGE_ID, FALSE);
#endif
    //SxTimer_SetFuncActive(SX_TIMER_DET_TIMER_ID, FALSE);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);

    Ux_Redraw();
    BurnIn_DrawStatus("Delete files...", CLRID_IDX_ORANGE, TRUE);
    BKG_PostEvent(NVTEVT_BKW_DELALL);

    //Ux_OpenWindow((VControl *)(&KeyTestWndCtrl), 0);

    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    g_bBurnInWndOpen = FALSE;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnKeyPower(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    if (g_uiLoopCount == g_uiLoopCountMax)
    {
        Ux_PostEvent(NVTEVT_SYSTEM_SHUTDOWN, 1, 0); // shutdown start
    }
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch (g_uiBurnInState)
    {
    case BURNIN_ST_KEY:
        g_uiBurnInState = BURNIN_ST_LCD;
        #if (LCD_TEST_IN_LOOP == ENABLE)
        g_uiLoopCount++;
        #endif
        //DrvWiFi_PowerOn(); // turn on WiFi power but don't need to connect
        Ux_OpenWindow((VControl *)(&LCDTestWndCtrl), 0);
        break;

    case BURNIN_ST_LCD:
        //Delay_DelayMs(1000); // delay for a while to wait for system ready
        g_uiBurnInState = BURNIN_ST_REC;
        #if (LCD_TEST_IN_LOOP == DISABLE)
        g_uiLoopCount++;
        #endif
        MovieRecTestWnd_SetRecTime(BURNIN_REC_TIME); // set recording time
        MovieRecTestWnd_SetAudioGain(0); // set audio gain to min
        Ux_OpenWindow((VControl *)(&MovieRecTestWndCtrl), 0);
        break;

    case BURNIN_ST_REC:
        //Delay_DelayMs(1000); // delay for a while to wait for system ready
        g_uiBurnInState = BURNIN_ST_PLAY;
        MoviePlayTestWnd_SetAudioVolume(0); // set audio volume to min
        MoviePlayTestWnd_SetPlayReserveSec(2);
        Ux_OpenWindow((VControl *)(&MoviePlayTestWndCtrl), 0);
        break;

    case BURNIN_ST_PLAY:
        if (g_uiLoopCount == g_uiLoopCountMax)
        {
            // show result
            Ux_Redraw();
            BurnIn_DrawLoopCount(TRUE);
            BurnIn_DrawStatus("Test Finished!", CLRID_IDX_GREEN, TRUE);
            BurnIn_DrawTips("Press Power key to turn off");
        }
        else
        {
            #if (LCD_TEST_IN_LOOP == ENABLE)
            //Delay_DelayMs(1000); // delay for a while to wait for system ready
            g_uiBurnInState = BURNIN_ST_LCD;
            g_uiLoopCount++;
            Ux_OpenWindow((VControl *)(&LCDTestWndCtrl), 0);
            #else
            //Delay_DelayMs(1000); // delay for a while to wait for system ready
            g_uiBurnInState = BURNIN_ST_REC;
            g_uiLoopCount++;
            MovieRecTestWnd_SetRecTime(BURNIN_REC_TIME); // set recording time
            MovieRecTestWnd_SetAudioGain(0); // set audio gain to min
            Ux_OpenWindow((VControl *)(&MovieRecTestWndCtrl), 0);
            #endif
        }
        break;

    default:
        break;
    }

    //Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray); // marked; issue the event will cause window redraw
    return NVTEVT_CONSUME;
}

INT32 BurnInWnd_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    NVTEVT  event;

    event = paramArray[ONDONE_PARAM_INDEX_CMD];

    switch(event)
    {
    case NVTEVT_BKW_DELALL:
        FileDB_Refresh(0);
        Ux_OpenWindow((VControl *)(&KeyTestWndCtrl), 0);
        break;

    default:
        break;
    }

    return NVTEVT_CONSUME;
}

