//This source code is generated by UI Designer Studio.

#ifndef KEYTESTWND_H
#define KEYTESTWND_H

#include "UIFramework.h"

extern VControl KeyTestWndCtrl;//Panel type 

//---------------------KeyTestWndCtrl User Export---------------------------
#endif
