//This source code is generated by UI Designer Studio.

#ifndef LCDTESTWND_H
#define LCDTESTWND_H

#include "UIFramework.h"

extern VControl LCDTestWndCtrl;//Panel type 

extern VControl LCDTestWnd_Panel1Ctrl;//Panel type 

//---------------------LCDTestWndCtrl User Export---------------------------
#endif
