//This source code is generated by UI Designer Studio.

#ifndef LEDTESTWND_H
#define LEDTESTWND_H

#include "UIFramework.h"

extern VControl LEDTestWndCtrl;//Panel type 

//---------------------LEDTestWndCtrl User Export---------------------------
#endif
