//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "LEDTestWndRes.c"
#include "LEDTestWnd.h"
#include "PrjCfg.h"

//---------------------LEDTestWndCtrl Debug Definition -----------------------------
#define _LEDTESTWND_ERROR_MSG        1
#define _LEDTESTWND_TRACE_MSG        0

#if (_LEDTESTWND_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define LEDTestWndErrMsg(...)            debug_msg ("^R LEDTestWnd: "__VA_ARGS__)
#else
#define LEDTestWndErrMsg(...)
#endif

#if (_LEDTESTWND_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define LEDTestWndTraceMsg(...)          debug_msg ("^B LEDTestWnd: "__VA_ARGS__)
#else
#define LEDTestWndTraceMsg(...)
#endif

//---------------------LEDTestWndCtrl Global Variables -----------------------------

//---------------------LEDTestWndCtrl Prototype Declaration  -----------------------

//---------------------LEDTestWndCtrl Public API  ----------------------------------

//---------------------LEDTestWndCtrl Private API  ---------------------------------
//---------------------LEDTestWndCtrl Control List---------------------------
CTRL_LIST_BEGIN(LEDTestWnd)
CTRL_LIST_END

//----------------------LEDTestWndCtrl Event---------------------------
INT32 LEDTestWnd_OnOpen(VControl *, UINT32, UINT32 *);
INT32 LEDTestWnd_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(LEDTestWnd)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,LEDTestWnd_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,LEDTestWnd_OnClose)
EVENT_END

INT32 LEDTestWnd_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 LEDTestWnd_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
