//This source code is generated by UI Designer Studio.

#ifndef MOVIEPLAYTESTWND_H
#define MOVIEPLAYTESTWND_H

#include "UIFramework.h"

extern VControl MoviePlayTestWndCtrl;//Panel type

//---------------------MoviePlayTestWndCtrl User Export---------------------------
extern void MoviePlayTestWnd_SetAudioVolume(UINT32 uiVolume);
extern void MoviePlayTestWnd_SetPlayReserveSec(UINT32 uiSec);

#endif
