#ifndef _IPL_CTRLINFOR_H_
#define _IPL_CTRLINFOR_H_

/**
    IPL_CtrlInfor.h


    @file       IPL_CtrlInfor.h
    @ingroup    mISYSAlg
    @note       Nothing (or anything need to be mentioned).

    Copyright   Novatek Microelectronics Corp. 2011.  All rights reserved.
*/
#include "Type.h"
#include "ErrorNo.h"

/**
    default information for Image-Pipeline
*/
typedef enum {
	IPLCTRL_PRVFLOW = 0,
	IPLCTRL_CAPFLOW,

	IPLCTRL_FUNC_EN,
	IPLCTRL_EXT_CTRL_EN,
	IPLCTRL_CFMODEEXT,  // ref. to IPLCFModeExt
	IPLCTRL_GROUP_IDX,
	IPLCTRL_ORDER_IDX,
	IPLCTRL_SEN_MODE,
	IPLCTRL_MF_BASE_ID,
	IPLCTRL_MF_TOTAL_FRM_BIT,
	IPLCTRL_MF_TOTAL_FRM_NUM,

	IPLCTRL_PRVBURSTLENGTH,
	IPLCTRL_CAPBURSTLENGTH,

	IPLCTRL_SIE_VD_INV,
	IPLCTRL_SIE_HD_INV,
	IPLCTRL_SIE_VD_PHASE,
	IPLCTRL_SIE_HD_PHASE,
	IPLCTRL_SIE_DATA_PHASE,

	IPLCTRL_CUR_MODE,

	IPLCTRL_SEN_PRV_CROP_RATIO,
	IPLCTRL_SEN_CAP_CROP_RATIO,

	IPLCTRL_SIE_CH3_CAP_SUBRATIO,

	IPLCTRL_PRVAUTO_OB_EN,
	IPLCTRL_CAPAUTO_OB_EN,
	IPLCTRL_CAPDF_EN,

	IPLCTRL_SIE_IN_OFS_X,
	IPLCTRL_SIE_IN_OFS_Y,

	IPLCTRL_SIE_PRVSTPIX,
	IPLCTRL_SIE_CH0_PRVBIT,
	IPLCTRL_SIE_CH3_PRVBIT,

	IPLCTRL_SIE_CAPSTPIX,
	IPLCTRL_SIE_CH0_CAPBIT,
	IPLCTRL_SIE_CH3_CAPBIT,

	IPLCTRL_SIE_PRVCROP_START_X,
	IPLCTRL_SIE_PRVCROP_START_Y,
	IPLCTRL_SIE_PRVCROP_SIZE_H,
	IPLCTRL_SIE_PRVCROP_SIZE_V,

	IPLCTRL_SIE_CAPCROP_SIZE_H,
	IPLCTRL_SIE_CAPCROP_SIZE_V,

	IPLCTRL_SIE_CH0_RAWENC_EN,          //RAW ENCODE ON/OFF, always set to ON
	IPLCTRL_SIE_CH0_RAWENC_BUF_RATIO,   //RAW ENCODE Buffer ratio, raw buffer = (((lineoffset*bitdepth/8)*ratio)/100)*height
	IPLCTRL_SIE_DISABLE_RAWENC_MANUAL,  //RAW ENCODE ON/OFF Switch, only for debug using

	IPLCTRL_SIE_CH0_RAW_EN,
	IPLCTRL_SIE_CH0_RAW_BUFNUM,
	IPLCTRL_SIE_CH0_RAW_SIZE_H,
	IPLCTRL_SIE_CH0_RAW_SIZE_HLOS,
	IPLCTRL_SIE_CH0_RAW_SIZE_V,
	IPLCTRL_SIE_CH0_RAW_1STSTRP_LOS,

	IPLCTRL_SIE_CH0_CAP_RAW_SIZE_H,
	IPLCTRL_SIE_CH0_CAP_RAW_SIZE_HLOS,
	IPLCTRL_SIE_CH0_CAP_RAW_SIZE_V,
	IPLCTRL_SIE_CH0_CAP_RAW_DATAFMT,
	IPLCTRL_SIE_CH0_CAP_RAW_HDR_BASE_ID,
	IPLCTRL_SIE_CH0_CAP_RAW_HDR_TOTAL_FRM,
	IPLCTRL_SIE_CH0_CAP_RAW_HDR_FRM_BIT,

	IPLCTRL_SIE_CH1_CAP_CA_EN,
	IPLCTRL_SIE_CH1_CAP_CA_WINXNUM,
	IPLCTRL_SIE_CH1_CAP_CA_WINYNUM,

	IPLCTRL_SIE_CH1_EN,
	IPLCTRL_SIE_CA_EN,

	IPLCTRL_SIE_CH1_BUFNUM,
	IPLCTRL_SIE_CH1_H_FLIP,
	IPLCTRL_SIE_CH1_V_FLIP,
	IPLCTRL_SIE_CA_WINXNUM,
	IPLCTRL_SIE_CA_WINYNUM,

	IPLCTRL_SIE_LA_EN,
	IPLCTRL_SIE_LA_BUFNUM,
	IPLCTRL_SIE_LA_WINXNUM,
	IPLCTRL_SIE_LA_WINYNUM,

	IPLCTRL_SIE_CH3_EN,
	IPLCTRL_SIE_CH3_SRC,
	IPLCTRL_SIE_CH3_BUFNUM,
	IPLCTRL_SIE_CH3_SIZE_H,
	IPLCTRL_SIE_CH3_SIZE_HLOS,
	IPLCTRL_SIE_CH3_SIZE_V,
	IPLCTRL_SIE_CH3_YOUT_WINXNUM,
	IPLCTRL_SIE_CH3_YOUT_WINYNUM,
	IPLCTRL_SIE_CH3_CAP_RAW_SIZE_H,
	IPLCTRL_SIE_CH3_CAP_RAW_SIZE_HLOS,
	IPLCTRL_SIE_CH3_CAP_RAW_SIZE_V,

	IPLCTRL_SIE_CH4_EN,
	IPLCTRL_SIE_CH4_SRC,
	IPLCTRL_SIE_CH4_BUFNUM,
	IPLCTRL_SIE_CH4_SIZE_H,
	IPLCTRL_SIE_CH4_SIZE_HLOS,
	IPLCTRL_SIE_CH4_SIZE_V,

	IPLCTRL_IPL_IN_OFS_X,
	IPLCTRL_IPL_IN_OFS_Y,

	IPLCTRL_IPL_IN_BIT,
	IPLCTRL_IPL_IN_START_X,
	IPLCTRL_IPL_IN_START_Y,
	IPLCTRL_IPL_IN_SIZE_H,
	IPLCTRL_IPL_IN_SIZE_HLOS,
	IPLCTRL_IPL_IN_SIZE_V,
	IPLCTRL_IPL_IN_RSC_CROP_RATIO,
	IPLCTRL_IPL_IN_DIS_CROP_RATIO,

	IPLCTRL_RHE_DEFOG_SUB_OUT_EN,
	IPLCTRL_RHE_DEFOG_SUB_OUT_SIZE,

	IPLCTRL_IPE_ETH_OUT_EN,
	IPLCTRL_IPE_ETH_OUT_SIZE_H,
	IPLCTRL_IPE_ETH_OUT_SIZE_HLOS,
	IPLCTRL_IPE_ETH_OUT_SIZE_V,

	IPLCTRL_IME_CAP_SUBRATIO,

	IPLCTRL_IFE2_LCA_EN,
	IPLCTRL_IME_SUB_OUT_BUF_NUM,
	IPLCTRL_IME_SUB_OUT_BUF_FMT,
	IPLCTRL_IME_SUB_OUT_BUF_SIZE_H,
	IPLCTRL_IME_SUB_OUT_BUF_SIZE_V,
	IPLCTRL_IME_SUB_OUT_BUF_SIZE_YLOS,

	IPLCTRL_IME_SCALE_RATIO_THR,
	IPLCTRL_IME_SCALER_OVER,
	IPLCTRL_IME_SCALER_UNDER,

	IPLCTRL_IME_PRI_MASK_EN,
	IPLCTRL_IME_PRI_MASK_H,
	IPLCTRL_IME_PRI_MASK_V,

	IPLCTRL_IME_P1_EN,
	IPLCTRL_IME_P1_SAMPLE_RATE,
	IPLCTRL_IME_P1_ENC_EN,
	IPLCTRL_IME_P1_ENC_FMT,
	IPLCTRL_IME_P1_IMG_FMT,
	IPLCTRL_IME_P1_OUT_SIZE_H,
	IPLCTRL_IME_P1_OUT_SIZE_HLOS,
	IPLCTRL_IME_P1_OUT_SIZE_V,
	IPLCTRL_IME_P1_OUT_CROP_STR_X,
	IPLCTRL_IME_P1_OUT_CROP_STR_Y,
	IPLCTRL_IME_P1_OUT_CROP_H,
	IPLCTRL_IME_P1_OUT_CROP_V,
	IPLCTRL_IME_P1_SQUARE_EN,
	IPLCTRL_IME_P1_SPRT_YBUFOFS,
	IPLCTRL_IME_P1_SPRT_CBUFOFS,

	IPLCTRL_IME_P2_EN,
	IPLCTRL_IME_P2_SAMPLE_RATE,
	IPLCTRL_IME_P2_IMG_FMT,
	IPLCTRL_IME_P2_OUT_SIZE_H,
	IPLCTRL_IME_P2_OUT_SIZE_HLOS,
	IPLCTRL_IME_P2_OUT_SIZE_V,
	IPLCTRL_IME_P2_OUT_CROP_STR_X,
	IPLCTRL_IME_P2_OUT_CROP_STR_Y,
	IPLCTRL_IME_P2_OUT_CROP_H,
	IPLCTRL_IME_P2_OUT_CROP_V,
	IPLCTRL_IME_P2_SPRT_YBUFOFS,
	IPLCTRL_IME_P2_SPRT_CBUFOFS,

	IPLCTRL_IME_P3_EN,
	IPLCTRL_IME_P3_SAMPLE_RATE,
	IPLCTRL_IME_P3_IMG_FMT,
	IPLCTRL_IME_P3_OUT_SIZE_H,
	IPLCTRL_IME_P3_OUT_SIZE_HLOS,
	IPLCTRL_IME_P3_OUT_SIZE_V,
	IPLCTRL_IME_P3_OUT_CROP_STR_X,
	IPLCTRL_IME_P3_OUT_CROP_STR_Y,
	IPLCTRL_IME_P3_OUT_CROP_H,
	IPLCTRL_IME_P3_OUT_CROP_V,
	IPLCTRL_IME_P3_SPRT_YBUFOFS,
	IPLCTRL_IME_P3_SPRT_CBUFOFS,

	IPLCTRL_IME_P4_EN,
	IPLCTRL_IME_P4_SAMPLE_RATE,
	IPLCTRL_IME_P4_IMG_FMT,
	IPLCTRL_IME_P4_OUT_SIZE_H,
	IPLCTRL_IME_P4_OUT_SIZE_HLOS,
	IPLCTRL_IME_P4_OUT_SIZE_V,
	IPLCTRL_IME_P4_OUT_CROP_STR_X,
	IPLCTRL_IME_P4_OUT_CROP_STR_Y,
	IPLCTRL_IME_P4_OUT_CROP_H,
	IPLCTRL_IME_P4_OUT_CROP_V,
	IPLCTRL_IME_P4_EXTOUT_EN,
	IPLCTRL_IME_P4_EDGEMAP_BUFOFS,
	IPLCTRL_IME_P4_HISTO_BUFOFS,

	IPLCTRL_IME_P5_EN,
	IPLCTRL_IME_P5_SAMPLE_RATE,
	IPLCTRL_IME_P5_IMG_FMT,
	IPLCTRL_IME_P5_OUT_SIZE_H,
	IPLCTRL_IME_P5_OUT_SIZE_HLOS,
	IPLCTRL_IME_P5_OUT_SIZE_V,
	IPLCTRL_IME_P5_OUT_CROP_STR_X,
	IPLCTRL_IME_P5_OUT_CROP_STR_Y,
	IPLCTRL_IME_P5_OUT_CROP_H,
	IPLCTRL_IME_P5_OUT_CROP_V,
	IPLCTRL_IME_P5_SPRT_YBUFOFS,
	IPLCTRL_IME_P5_SPRT_CBUFOFS,

	IPLCTRL_IME_OUT_GROUP_BUF_ARRANGE,
	IPLCTRL_IME_OUT_GROUP_TOTAL_NUM_H,
	IPLCTRL_IME_OUT_GROUP_TOTAL_NUM_V,
	IPLCTRL_IME_OUT_GROUP_POS_H,
	IPLCTRL_IME_OUT_GROUP_POS_V,

	IPLCTRL_DIS_RATIO,
	IPLCTRL_MSNR_CAP_EN,
	IPLCTRL_WDR_CAP_EN,
	IPLCTRL_SHDR_CAP_EN,
	IPLCTRL_DEFOG_CAP_EN,
	IPLCTRL_EXT_FUNC_EN,
	IPLCTRL_SENSOR_TYPE,
    IPLCTRL_FLIP_TYPE,
	IPLCTRL_IME_SQUARE_REF_PATH_SEL,

    IPLCTRL_VR360_4SPLIT_EN,
    IPLCTRL_VR360_IME_P1_EXT_WIDTH,
    IPLCTRL_VR360_IME_P2_EXT_WIDTH,
    IPLCTRL_VR360_IME_P3_EXT_WIDTH,
    IPLCTRL_VR360_IME_P4_EXT_WIDTH,
    IPLCTRL_VR360_IME_P5_EXT_WIDTH,

	IPLCTRL_MAX_CNT_DEF,
	ENUM_DUMMY4WORD(IPLCTRL_IDX_DEF)
} IPLCTRL_IDX_DEF;

#define IPL_CTRL_ELEMENT_MAX 200
#define IPL_CTRL_NO_USE 0xffffffff

/**
     set ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @param[in] UINT32 value
*/
extern void IPL_CtrlSetInfor(UINT32 Id, UINT32 Idx, UINT32 Value);

/**
     get ctrl information

     @param[in] IPL_PROC_ID ipl process id
     @param[in] UINT32 idx, depend on IPL lib
     @return [UINT32]
         - @b value
*/
extern UINT32 IPL_CtrlGetInfor(UINT32 Id, UINT32 Idx);

/**
     initial ctrl information

     @note reset all array information.
     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforInit(void);

/**
     un-initial ctrl information

     @note reset all array information.

     @return (ER)
         - @b E_OK: SUCCESS
         - @b E_SYS: FAIL
*/
extern ER IPL_CtrlInforUnInit(void);

#endif //_IPL_CTRLINFOR_H_
