//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONOPTION_H
#define MENUCOMMONOPTION_H

#include "UIFramework.h"

extern VControl MenuCommonOptionCtrl;//Panel type

extern VControl MenuCommonOption_ListCtrl;//List type

typedef enum {
	MenuCommonOption_List_ICON_MODE_CAPTURE_M,
	MenuCommonOption_List_ICON_CLOUD_ON_M,
	MenuCommonOption_List_ICON_WIFI_ON_M,
	MenuCommonOption_List_ICON_WIFI_OFF_M,
	MenuCommonOption_List_MAX
} MenuCommonOption_List_Setting;

extern VControl MenuCommonOption_TitleCtrl;//Menu type

typedef enum {
	MenuCommonOption_Title_STRID_WIFI,
	MenuCommonOption_Title_MAX
} MenuCommonOption_Title_Setting;

extern VControl MenuCommonOption_StatusCtrl;//Menu type

typedef enum {
	MenuCommonOption_Status_STRID_WIFI_OFF,
	MenuCommonOption_Status_MAX
} MenuCommonOption_Status_Setting;

extern VControl MenuCommOption_PanelCtrl;//Panel type

extern VControl MenuCommonOption_LeftCtrl;//Static type

extern VControl MenuCommonOption_RightCtrl;//Static type

extern VControl MenuCommonOption_LeftIconCtrl;//Static type

extern VControl MenuCommonOption_RightIconCtrl;//Static type

//---------------------MenuCommonOptionCtrl User Export---------------------------
#endif
