//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "MenuCommonItemRes.c"
#include "MenuCommonItem.h"
#include "PrjCfg.h"
#include "UIFlow.h"
extern UINT32 System_GetEnableSensor(void);

//---------------------MenuCommonItemCtrl Debug Definition -----------------------------
#define _MENUCOMMONITEM_ERROR_MSG        1
#define _MENUCOMMONITEM_TRACE_MSG        0

#if (_MENUCOMMONITEM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define MenuCommonItemErrMsg(...)            debug_msg ("^R MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemErrMsg(...)
#endif

#if (_MENUCOMMONITEM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define MenuCommonItemTraceMsg(...)          debug_msg ("^B MenuCommonItem: "__VA_ARGS__)
#else
#define MenuCommonItemTraceMsg(...)
#endif

//---------------------MenuCommonItemCtrl Global Variables -----------------------------
#define PAGE           4
//---------------------MenuCommonItemCtrl Prototype Declaration  -----------------------
#if defined(_KEY_METHOD_4KEY_)
#define MENU_KEY_PRESS_MASK        (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_UP|FLGKEY_DOWN|FLGKEY_RIGHT|FLGKEY_SHUTTER2)
#else
#define MENU_KEY_PRESS_MASK        (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_RELEASE_MASK      (FLGKEY_LEFT|FLGKEY_RIGHT)
#define MENU_KEY_CONTINUE_MASK     (FLGKEY_LEFT|FLGKEY_RIGHT)
#endif
//---------------------MenuCommonItemCtrl Public API  ----------------------------------

//---------------------MenuCommonItemCtrl Private API  ---------------------------------
static TM_MENU *g_pItemMenu = 0;

static void MenuCommonItem_SetCurrentMenu(TM_MENU *pMenu)
{
	g_pItemMenu = pMenu;
}
static TM_MENU *MenuCommonItem_GetCurrentMenu(void)
{
	return g_pItemMenu;
}
static void MenuCommonItem_UpdateContent(TM_MENU *pMenu)
{
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	UINT32      i;
	UINT16      startIndex = 0;
	UINT16      itemIndex = 0;

	pPage = &pMenu->pPages[pMenu->SelPage];
	pItem = &pPage->pItems[pPage->SelItem];
	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];

	if (pItem->Count) {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, TRUE);
		if (pOption->TextId & STRID_USER_START) {
			UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pOption->TextId)));
		} else {
			UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);
		}
	} else if (pItem->ItemId == IDM_COMMON_MENU) {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, TRUE);
		UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  STRID_SETUP);
	} else {
		UxCtrl_SetShow(&MenuCommonItem_StatusCtrl, FALSE);
	}

	if (pItem->TextId & STRID_USER_START) {
		UxMenu_SetItemData(&MenuCommonItem_TitleCtrl, 0, MNUITM_STRID,  Txt_Pointer(UIRes_GetUserString(pItem->TextId)));
	} else {
		UxMenu_SetItemData(&MenuCommonItem_TitleCtrl, 0, MNUITM_STRID,  pItem->TextId);
	}
	//find startIndex
	TM_FindStartIndex(pMenu, PAGE, &startIndex);

	//draw item form startIndex
	itemIndex = startIndex;
	for (i = 0; i < PAGE; i++) {
		//check item if disable
		TM_CheckItemStatus(pMenu, &itemIndex, TRUE);
		if ((itemIndex == pPage->Count) && (i < PAGE)) {
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STATUS, STATUS_DISABLE);
		} else {
			pItem = &pPage->pItems[itemIndex];
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STATUS, STATUS_ENABLE);
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_STRID,  pItem->TextId);
			UxList_SetItemData(&MenuCommonItem_ListCtrl, i, LSTITM_ICONID, pItem->IconId);
			itemIndex++;
		}
	}
}
static void MenuCommonItem_UpdatePosition(void)
{
	ISIZE str_size;
	Ux_RECT MenuRect, NewRect;
	UINT32 strId = UxMenu_GetItemData(&MenuCommonItem_TitleCtrl, CURITEM_INDEX, MNUITM_STRID);

	//avoid other tmp UI change font table
	GxGfx_SetTextStroke((const FONT *)gDemoKit_Font, FONTSTYLE_NORMAL, SCALE_1X);

	if (strId & TEXT_POINTER) {
		strId = (strId) & ~TEXT_POINTER;
		GxGfx_TextPrint(0, 0, 0, "%s", strId);
	} else {
		GxGfx_Text(0, 0, 0, GxGfx_GetStringID(strId));
	}

	str_size = GxGfx_GetTextLastSize();
	UxCtrl_GetPos(&MenuCommonItem_TitleCtrl, &MenuRect);
	UxCtrl_GetPos(&MenuCommonItem_StatusCtrl, &NewRect);
	NewRect.x1 = MenuRect.x1 + str_size.w + 5   ;
	UxCtrl_SetPos(&MenuCommonItem_StatusCtrl, NewRect);
}
//---------------------MenuCommonItemCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommonItem)
CTRL_LIST_ITEM(MenuCommonItem_List)
CTRL_LIST_ITEM(MenuCommonItem_Title)
CTRL_LIST_ITEM(MenuCommonItem_Status)
#if defined(_KEY_METHOD_2KEY_)
CTRL_LIST_ITEM(MenuCommItem_Panel)
#endif
CTRL_LIST_END

//----------------------MenuCommonItemCtrl Event---------------------------
INT32 MenuCommonItem_OnOpen(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_OnStorageChange(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, MenuCommonItem_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, MenuCommonItem_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE, MenuCommonItem_OnChildClose)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, MenuCommonItem_OnStorageChange)
EVENT_END


INT32 MenuCommonItem_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	TM_ITEM    *pModeItem;
	INT32      curMode = 0;
	UINT32		sensor;

	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);

	if (UI_GetData(FL_WIFI_LINK) == WIFI_LINK_OK && UI_GetData(FL_NetWorkMode) == NET_STATION_MODE) {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_ON);
	} else {
		SysSetFlag(FL_COMMON_CLOUD, CLOUD_OFF);
	}

	sensor = System_GetEnableSensor();
	if (sensor == (SENSOR_1 | SENSOR_2) ||
		sensor == (SENSOR_1 | SENSOR_3) ||
		sensor == (SENSOR_1 | SENSOR_4) ||
		sensor == (SENSOR_2 | SENSOR_3) ||
		sensor == (SENSOR_2 | SENSOR_4) ||
		sensor == (SENSOR_3 | SENSOR_4)) { // dual sensor
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_TRI_1920x1080P30,    TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_QUAD_1920x1080P30,   TM_OPTION_DISABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30,  TM_OPTION_DISABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1920x1080P120, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1280x720P240,  TM_OPTION_DISABLE);
	} else if (
		sensor == (SENSOR_1 | SENSOR_2 | SENSOR_3) ||
		sensor == (SENSOR_1 | SENSOR_2 | SENSOR_4) ||
		sensor == (SENSOR_1 | SENSOR_3 | SENSOR_4) ||
		sensor == (SENSOR_2 | SENSOR_3 | SENSOR_4)) { // tri sensor
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_TRI_1920x1080P30,   TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_QUAD_1920x1080P30,  TM_OPTION_DISABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30,  TM_OPTION_DISABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1920x1080P120, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1280x720P240,  TM_OPTION_DISABLE);
	} else if (
		sensor == (SENSOR_1 | SENSOR_2 | SENSOR_3 | SENSOR_4)) { // quad sensor
		CHKPNT;
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_TRI_1920x1080P30,   TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_QUAD_1920x1080P30,  TM_OPTION_ENABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30,  TM_OPTION_DISABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60,  TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1920x1080P120, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1280x720P240,  TM_OPTION_DISABLE);
	} else {
#if (SENSOR_CAPS_COUNT > 1)
		TM_SetItemStatus(&gMovieMenu, IDM_MOVIE_DUAL_CAM, TM_ITEM_DISABLE);
		TM_SetItemStatus(&gPhotoMenu, IDM_DUAL_CAM, TM_ITEM_DISABLE);
#endif
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_DUAL_1920x1080P30_1920x1080P30, TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_TRI_1920x1080P30,   TM_OPTION_DISABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_QUAD_1920x1080P30,  TM_OPTION_DISABLE);
#if (SMALL_CLONE_MOVIE == DISABLE)
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2880x2160P50,  TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_3840x2160P30, TM_OPTION_ENABLE);
		//TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2704x2032P60,  TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_2560x1440P60, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1920x1080P120, TM_OPTION_ENABLE);
		TM_SetOptionStatus(&gMovieMenu, IDM_MOVIE_SIZE, MOVIE_SIZE_FRONT_1280x720P240,  TM_OPTION_ENABLE);
#endif
	}

	MenuCommonItem_SetCurrentMenu(&gCommonMenu);
	pMenu = MenuCommonItem_GetCurrentMenu();

	pMenu->Status = TMS_ON_ITEM;
	pMenu->SelPage = 0;         // reset page to 0

	pPage = &pMenu->pPages[pMenu->SelPage];
	pPage->SelItem = 0;           // reset item to 0
	//check item if disable
	TM_CheckItemStatus(pMenu, &pPage->SelItem, TRUE);

	pItem = &pPage->pItems[pPage->SelItem];
	pOption = &pItem->pOptions[SysGetFlag(pItem->SysFlag)];

	UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);
	UxList_SetData(&MenuCommonItem_ListCtrl, LST_CURITM, 0);

	curMode = System_GetState(SYS_STATE_CURRMODE);
	if (curMode == PRIMARY_MODE_PHOTO) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_CAPTURE_M;
		pModeItem->TextId = STRID_CAP_MODE;
	} else if (curMode == PRIMARY_MODE_MOVIE) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_VIDEO_M;
		pModeItem->TextId = STRID_MOVIE;
	} else if (curMode == PRIMARY_MODE_PLAYBACK) {
		pModeItem = &pPage->pItems[1];
		pModeItem->IconId = ICON_MODE_PLAYBACK_M;
		pModeItem->TextId = STRID_PLAYBACK;
	}

	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();

	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_PRESS_MASK);
	Input_SetKeySoundMask(KEY_PRESS, MENU_KEY_PRESS_MASK);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);

	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);

	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_DEFAULT);

	//#NT#2016/08/19#Lincy Lin#[0106935] -begin
	//#NT# Support change WDR, SHDR, RSC setting will change mode after exit menu
	BOOL bReOpenMovie = FlowMovie_CheckReOpenItem();
	BOOL bReOpenPhoto = FlowPhoto_CheckReOpenItem();

	if(bReOpenMovie)
		exam_msg("RESTART_MODE_YES\r\n");
	else
		exam_msg("RESTART_MODE_NO\r\n");

	if (bReOpenMovie || bReOpenPhoto)
		//#NT#2016/08/19#Lincy Lin -end
	{
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
	}

	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu = MenuCommonItem_GetCurrentMenu();
	//UINT32      uiItem ,uiOption;

	pMenu->Status = TMS_ON_ITEM;
	MenuCommonItem_UpdateContent(pMenu);
	MenuCommonItem_UpdatePosition();
	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_DEFAULT);
	Ux_DefaultEvent(pCtrl, NVTEVT_CHILD_CLOSE, paramNum, paramArray);

	if (paramNum >= 2) {
		//uiItem = paramArray[0];
		//uiOption = paramArray[1];
	}
	Input_SetKeyMask(KEY_PRESS, MENU_KEY_PRESS_MASK);
	Input_SetKeyMask(KEY_RELEASE, MENU_KEY_RELEASE_MASK);
	Input_SetKeyMask(KEY_CONTINUE, MENU_KEY_CONTINUE_MASK);

	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}
//----------------------MenuCommonItem_ListCtrl Event---------------------------
INT32 MenuCommonItem_List_OnKeyNext(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeyPrev(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeySelect(VControl *, UINT32, UINT32 *);
INT32 MenuCommonItem_List_OnKeyExit(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MenuCommonItem_List)
EVENT_ITEM(NVTEVT_KEY_NEXT, MenuCommonItem_List_OnKeyNext)
EVENT_ITEM(NVTEVT_KEY_PREV, MenuCommonItem_List_OnKeyPrev)
EVENT_ITEM(NVTEVT_KEY_SELECT, MenuCommonItem_List_OnKeySelect)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2, MenuCommonItem_List_OnKeyExit)
EVENT_END

INT32 MenuCommonItem_List_OnKeyNext(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;

	if (paramNum == 1) {
		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			pMenu = MenuCommonItem_GetCurrentMenu();
			pPage = &pMenu->pPages[pMenu->SelPage];
			pPage->SelItem++;
			//check item if disable
			TM_CheckItemStatus(pMenu, &pPage->SelItem, TRUE);
			if (pPage->SelItem == pPage->Count) {
				// Close current UI Window now
				Ux_CloseWindow(&MenuCommonItemCtrl, 0);
			} else {
				MenuCommonItem_UpdateContent(pMenu);
				MenuCommonItem_UpdatePosition();
				Ux_SendEvent(pCtrl, NVTEVT_NEXT_ITEM, 0);
			}
		}
	}
	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_List_OnKeyPrev(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;

	if (paramNum == 1) {
		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			pMenu = MenuCommonItem_GetCurrentMenu();
			pPage = &pMenu->pPages[pMenu->SelPage];
			if (pPage->SelItem == 0) {
				// Close current UI Window now
				Ux_CloseWindow(&MenuCommonItemCtrl, 0);
			} else {
				pPage->SelItem--;
				//check item if disable
				TM_CheckItemStatus(pMenu, &pPage->SelItem, FALSE);
				if (pPage->SelItem == pPage->Count) {
					// Close current UI Window now
					Ux_CloseWindow(&MenuCommonItemCtrl, 0);
				} else {
					MenuCommonItem_UpdateContent(pMenu);
					MenuCommonItem_UpdatePosition();
					Ux_SendEvent(pCtrl, NVTEVT_PREVIOUS_ITEM, 0);
				}
			}
		}
	}
	return NVTEVT_CONSUME;
}
INT32 MenuCommonItem_List_OnKeySelect(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	TM_MENU    *pMenu;
	TM_PAGE    *pPage;
	TM_ITEM    *pItem;
	TM_OPTION  *pOption;
	TM_MENU    *pNextMenu;
	UINT32      SelOption = 0 ;

	if (paramNum == 1) {
		pMenu = MenuCommonItem_GetCurrentMenu();
		pPage = &pMenu->pPages[pMenu->SelPage];
		pItem = &pPage->pItems[pPage->SelItem];

		if (paramArray[0] == NVTEVT_KEY_PRESS) {
			if (pItem->Count != 0 && pItem->SysFlag != 0 && pItem->ItemId != IDM_COMMON_CLOUD) {
				SelOption = SysGetFlag(pItem->SysFlag);

				SelOption++;
				if (SelOption >= pItem->Count) {
					SelOption = 0;
				}

				SysSetFlag(pItem->SysFlag, SelOption);

				// toggle icon's string
				pOption = &pItem->pOptions[SelOption];
				UxMenu_SetItemData(&MenuCommonItem_StatusCtrl, 0, MNUITM_STRID,  pOption->TextId);

				TM_MENU_CALLBACK(pMenu, TMM_CONFIRM_OPTION, MAKE_LONG(pItem->ItemId, SelOption));
			} else {
				if (pItem->SysFlag == FL_COMMON_MODE) {
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gModeMenu);
				} else if (pItem->SysFlag == FL_COMMON_MENU) {
					// Enter 2nd level menu and pop up current mode's menu lists
					if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO) {
						pNextMenu = &gPhotoMenu;
					} else if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
						pNextMenu = &gPlaybackMenu;
					} else {
						pNextMenu = &gMovieMenu;
					}
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, (UINT32)pNextMenu);
				} else if (pItem->SysFlag == FL_COMMON_SETUP) {
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gSetupMenu);
				} else if (pItem->SysFlag == FL_COMMON_EXT_SETUP) {
					// Enter 2nd level menu and pop up various memu item.
					Ux_OpenWindow(&MenuCommonOptionCtrl, 1, &gExtSetupMenu);
				} else {
					MenuCommonItemErrMsg("not supp %d\r\n", pItem->SysFlag);
				}
			}
		}
	}

	return NVTEVT_CONSUME;
}

INT32 MenuCommonItem_List_OnKeyExit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	Ux_CloseWindow(&MenuCommonItemCtrl, 0);
	return NVTEVT_CONSUME;
}

//----------------------MenuCommonItem_TitleCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Title)
EVENT_END

//----------------------MenuCommonItem_StatusCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Status)
EVENT_END

//---------------------MenuCommItem_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MenuCommItem_Panel)
CTRL_LIST_ITEM(MenuCommonItem_Left)
CTRL_LIST_ITEM(MenuCommonItem_Right)
CTRL_LIST_ITEM(MenuCommonItem_LeftIcon)
CTRL_LIST_ITEM(MenuCommonItem_RightIcon)
CTRL_LIST_END

//----------------------MenuCommItem_PanelCtrl Event---------------------------
EVENT_BEGIN(MenuCommItem_Panel)
EVENT_END

//----------------------MenuCommonItem_LeftCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Left)
EVENT_END

//----------------------MenuCommonItem_RightCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_Right)
EVENT_END

//----------------------MenuCommonItem_LeftIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_LeftIcon)
EVENT_END

//----------------------MenuCommonItem_RightIconCtrl Event---------------------------
EVENT_BEGIN(MenuCommonItem_RightIcon)
EVENT_END

