//This source code is generated by UI Designer Studio.

#ifndef MENUCOMMONCONFIRM_H
#define MENUCOMMONCONFIRM_H

#include "UIFramework.h"

extern VControl MenuCommonConfirmCtrl;//Panel type

extern VControl MenuCommonConfirm_ListCtrl;//List type

typedef enum {
	MenuCommonConfirm_List_ICON_OK_M,
	MenuCommonConfirm_List_ICON_NO_M,
	MenuCommonConfirm_List_MAX
} MenuCommonConfirm_List_Setting;

extern VControl MenuCommonConfirm_TitleCtrl;//Static type

extern VControl MenuCommConfirm_PanelCtrl;//Panel type

extern VControl MenuCommonConfirm_LeftCtrl;//Static type

extern VControl MenuCommonConfirm_RightCtrl;//Static type

extern VControl MenuCommonConfirm_LeftIconCtrl;//Static type

extern VControl MenuCommonConfirm_RightIconCtrl;//Static type

//---------------------MenuCommonConfirmCtrl User Export---------------------------
#endif
