#include "UsbCmdID.h"
#include "SysKer.h"
#include "UsbCmdInt.h"
#include "UsbCmdAPI.h"
#include "PrjCfg.h"
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)

#define PRI_USBCMD                 10
#define STKSIZE_USBCMD             4096
#define STKSIZE_USBCMD_DOWNLOAD    2048


UINT32 USBCMDTSK_ID = 0;
UINT32 USBCMDTSK2_ID = 0;
UINT32 USBCMDDOWNLOADTSK_ID = 0;
UINT32 FLG_ID_USBCMD = 0;
UINT32 SEMID_USBCMD_1ST_COM = 0;

void UsbCmd_InstallID(void)
{
	OS_CONFIG_TASK(USBCMDTSK_ID, PRI_USBCMD, STKSIZE_USBCMD, UsbCmdTsk);
	OS_CONFIG_TASK(USBCMDTSK2_ID, PRI_USBCMD, STKSIZE_USBCMD, UsbCmdTsk2);
	OS_CONFIG_TASK(USBCMDDOWNLOADTSK_ID, PRI_USBCMD, STKSIZE_USBCMD_DOWNLOAD, UsbCmdDownloadTsk);
	OS_CONFIG_FLAG(FLG_ID_USBCMD);
	OS_CONFIG_SEMPHORE(SEMID_USBCMD_1ST_COM, 0, 1, 1);
}

#endif
//#NT#2016/05/31#Ben Wang -end
